### ISSUE TITLE
scroll image sequence

### ISSUE THREAD

**Issue by ahnnayi** [janpaepke/ScrollMagic#115]
Thank you for the wonderful plugin-! 
Is there a way to implement image sequence animation that cycles using ScrollMagic?

**Comment by burito1043** [comment]
I'm having trouble using multiple instances of this on the same page. I read to create separate scenes, but since I'm rather new to scroll magic, I"m not sure how to. Any help is appreciated...

**Comment by Berkmann18** [comment]
> ```js
> var scrollScene = new ScrollScene({duration: 100})
>                        .addTo(controller)
>                        .on("progress", function (e) {
>                             var current = Math.round(e.progress*(images.length-1));
>                             $("#myimg").attr("src", images[current]);
>                        });
> ```

This helped.
Thank you.
