### ISSUE TITLE
question: how to update pin spacers

### ISSUE THREAD

**Issue by sulram** [janpaepke/ScrollMagic#116]
hello there, could you help me on this situation?
I have some scenes, and each of them have the same height of window, updated in every window.resize.
when I'm in the last scene (scrollbar at the bottom) and scale down the window, the pin spacer is not resized, and I get an extra space.
how can I update its height?
if I scroll up to the begining of the page and then go down to the last slide, it correct the pin spacer height.
is there a method for that?
I've tried `controller.update(true)`, but nothing happens.
thank you very much

**Comment by vostokwork** [comment]
any updates?

 any updates?

 any updates?
