### ISSUE TITLE
Cannot get my the animation to stop for mobile widths

### ISSUE THREAD

**Issue by smeyer** [janpaepke/ScrollMagic#117]
I have tried everything under the sun it seems to get the animations to only work at a browser width of 769px and above.
I have seen this issue: https://github.com/janpaepke/ScrollMagic/issues/15

I've tried enabling/disabling and destroying the controller. I've tried setting the variables (including those for scenes) to null in addition to that. I've tried killing the TweenMax according to the Greensock documentation.

This is my first attempt to use your script. I don't know if my code is the most efficient or written ideally (I know I could use pinning but I got the functionality that I wanted the way that I wrote it). You can see my script here: https://gist.github.com/smeyer/25fe1f3b0b4ab7303b64

The page is here:
http://www.envisiondemo.com/hhs2/solutions/acute-care/

When I open the page at a width under 769px, it's fine. Then if I expand the window, the animations start working as they should, but if I try to reduce the window size, the animations remain active, and it makes the site look broken. I know that most people will not do this in normal usage, but I have to present this to the client who will want to see the responsive behavior as you expand and contract the browser.

Help please?

**Comment by eballeste** [comment]
@janpaepke Hi!

For some reason when trying to disable the controller for mobile views, it would not continue to work once the controller.enabled(true) was called. 

Disabling and enabling the scene, however, worked perfectly:

```
$(window).on("resize", function(e) {
  if ($(window).width() < 769 && scene.enabled()) {
    scene.enabled(false);
  } else if (!scene.enabled()) {
    scene.enabled(true);
  }
});
```

**Comment by Semyonmo** [comment]
@eballeste i find some solution, you need run update after change state of the controller.
```javascript
controller.update(true);
````
```javascript
$(window).on("resize", function(e) {
  if ($(window).width() < 769 && controller.enabled()) {
    controller.enabled(false);
  } else if (!controller.enabled()) {
    controller.enabled(true);
  }
  controller.update(true);
});
````

**Comment by redone75** [comment]
Here's a technique the works for me using Chris Coyier's "Done Resizing Event" for simplicity.
https://css-tricks.com/snippets/jquery/done-resizing-event/

```javascript
$(window).on('resize', function(e) {
    clearTimeout(resizeTimer);
    resizeTimer = setTimeout(function() {
        if ($(window).width() < 960 && controller.enabled()) {
            controller.enabled(false);
            body.addClass("resized-mobile");
        } else if (!controller.enabled()) {
            controller.enabled(true);
            body.removeClass("resized-mobile");
        }
        controller.update(true);
    }, 250);
});
```
I'm using the resized-mobile class added to the body to adjust elements that have been manipulated by scrollmagic in desktop view . In my example, I was only manipulating opacity and translate3d to restore the elements position/opacity to the desired location/state. Adjust accordingly.
```
body.resized-mobile ELEMENT-NAME {
    opacity: 1 !important;
    -webkit-transform: translate3d(0,0,0) !important;
    transform: translate3d(0,0,0) !important;
}
```

**Comment by saida** [comment]
Logical error fix:

```javascript
$(window).on('resize', function(){
  if ($('html').width() < 769) {
    if (controller.enabled()) {
      controller.enabled(false);
    }
  } else if (!controller.enabled()) {
    controller.enabled(true);
  }
  controller.update(true);
}).trigger('resize');
```
