### ISSUE TITLE
How can I overlap my animation?

### ISSUE THREAD

**Issue by ghost** [janpaepke/ScrollMagic#12]
First I want to say thank you for creating such a wonderful plugin. I am having a lot of fun using and learning it. 

What I am trying to accomplish is to have both animations in my timeline overlap when I scroll. I have a bunch of divs with the same class and style displayed inline block so it is like a train. Like the stagger animation in your example. The div on the far left also has a div ID. 

Right now what is happening is that when I scroll It will play the first animation as I scroll and when the end of the first animation is reached (stagger) then the second animation starts playing. 

I have tried adding a label to both of them and changing the time to the second one to -=.75 etc to get it to overlap but it still plays sequentially. How can I get both animations to overlap each other as I am scrolling? 

seven is the class name for the div boxes and #box7 is the id for the box on the far left that also has a class name of seven.   

``` javascript
 var tween = new TimelineMax();
    tween.add(
        TweenMax.staggerFromTo(".seven", 2, {left: 700}, {left: 0, color:"blue", ease:Back.easeOut}, 0.15)
    );

    tween.add(
        TweenMax.to("#box7", 2, {backgroundColor:"black", width:"+=400px", ease: Back.easeOut})
    );

    // build scene
    var scene = new ScrollScene({triggerElement: "#box7", duration:200, offset: -120})
                    .setTween(tween)
                    .addTo(controller);
```

**Comment by ahamill85** [comment]
Have you run in to any issues when using a set duration with a container height that matches that duration and using TimelineMax with multiple successive tweens? My timeline doesn't get fully run through and the the shorter the duration/height, the less the timeline gets run. Basically, if I set the duration/height to 1000, about 60% of the timeline gets played after scrolling the entire length, but if I increase the height/duration to 10000 about 90% of the timeline gets played. Thanks for any assistance you can provide!

```javascript
var tween = new TimelineMax()
    .fromTo('#heading-1', 5, { opacity: 0, top: '10vh' }, { opacity: 1 })
    .fromTo('#heading-2', 5, { opacity: 0, top: '80vh' }, { opacity: 1, top: '70vh' })
    .to('#heading-1', 5, { opacity: 0, top: '-10vh' })
    .to('#heading-2', 5, { opacity: 0, top: '80vh' })
    .fromTo('#para-1', 5, { opacity: 0, top: '10vh' }, { opacity: 1 });

$('.scrollContent').height(1000)

var controller = new ScrollMagic.Controller({ container: '#mobile-experience-wrapper' });

// init scene
var scene = new ScrollMagic.Scene({ duration: 2000 })
    .setTween(tween)
    .addTo(controller);
```

I wanted to be able to set the height of the scene dynamically based upon the TimelineMax.totalDuration() value. So if my total duration was 100 and I wanted 1 = 20px on the timeline my total scroll height/duration would be 2000px. Does that make sense?

**Comment by pdummermuth** [comment]
@ahamill85 have you been able to solve the problem? because right now I ran into the same problem :(

**Comment by ahamill85** [comment]
Yes, I'm pretty sure the issue was I wasn't taking in to consideration of the window height. The equation for setting the container height should be (totalTweenDuration * desiredMultiplier) - windowHeight. That explains why I was getting a varied scroll distance depending on the container height. It was all related to the ratio of the window to container height. I hope that helps.

**Comment by nawaaz91** [comment]
Hi,
Is it possible to execute two .fromTo statements in single step? how?
I have several wipe animation using .fromTo() but I want two .fromTo to trigger at the same time.
