### ISSUE TITLE
Animations not completing correctly

### ISSUE THREAD

**Issue by Dame1701** [janpaepke/ScrollMagic#134]
Hi Jan,

Firstly can I say what a great plugin this is, if I can get it working properly it's going to be awesome! Now onto my problem...

I have a very simple continuous page which contains all of my various page sections. Each page alternates in colour i.e. page 1 is black on white, page 2 is white on black etc. I am trying to use Scroll Magic to alternate my fixed top menu colours to be the opposite to the page colours so for example when I scroll to page 1, the top menu is white on black, page 2 the top menu is black on white etc.

My problem is when I scroll to the pages using the scroll bar, often the animations do not complete i.e. I scroll to the top of the page and the menu is black on light gray rather than white. Scroll magic then seems to get confused and can no animate until I refresh the page. If you scroll through the pages you'll see it sometimes work and sometimes doesn't

A link to my test page is here: 

http://fashionsite.dodsworthandgreen.com/

Scroll Magic is set up in the page-sizer.js script. I'm also using ScrollIt to scroll the page when the relevant menu section is clicked, however for testing I have remove this code temporarily.

I'm not sure if I'm doing something wrong of if this is a bug in ScrollMagic. It does look like something is going wrong somewhere with the plugin. It seems to happen more if you quickly scroll through the page.

Thanks for you advice and help,

Damien

**Comment by Sumit95** [comment]
Sir, i am the beginner. I couldnt see any kind of animations as it isnt working. I cant figure out the issue. Please help me.
![image](https://cloud.githubusercontent.com/assets/8403511/24143913/62b19fea-0e51-11e7-96bc-40b5774554d4.png)
![image](https://cloud.githubusercontent.com/assets/8403511/24143923/6b3daa3c-0e51-11e7-8611-48c104c97c4a.png)
![image](https://cloud.githubusercontent.com/assets/8403511/24143930/70737446-0e51-11e7-8897-d5bcc29a3ea6.png)
