### ISSUE TITLE
when scroll with high speed miss tweens 

### ISSUE THREAD

**Issue by GeorgeGeorgiev** [janpaepke/ScrollMagic#145]
Hi,
when you scroll with high speed like scrollTo with the plugin of tweenMax for 1 sek it miss the tweens...
Here is the example : http://ag.sitetester.biz/indexscm.html . The superscrollarama do the same thing. I don't know why it miss some tweens.

**Comment by jonnymarshall** [comment]
If anyone is looking for a solution to this in 2020, here's what worked for me:

`
const secondScene = new ScrollMagic.Scene({
    triggerElement: secondSceneTrigger
  }).on("start", e => {
    if (e.scrollDirection === "FORWARD") {
      // Forces first scene to be in end position
      firstSceneTimeline.totalProgress(1);
      // Forces current scene to play
      secondSceneTimeline.play();
    }
    if (e.scrollDirection === "REVERSE") {
      // Forces third scene to be in start position
      thirdSceneTimeline.totalProgress(0);
      // Forces current scene to play
      secondSceneTimeline.reverse();
    }
  }).addTo(controller);`

Essentially it forces previous timelines to their start or end position (depending on scroll direction) when each new trigger point is hit. Crucially it doesn't care about Timeline durations, so it will respond to fast scrolling in either direction.

Here's a gist for easy copy/pasting:
https://gist.github.com/jonnymarshall/78d9eafe52a15a94a534d9a6676030a2.js
