### ISSUE TITLE
Destroy/remove all for mobile

### ISSUE THREAD

**Issue by dkrause10** [janpaepke/ScrollMagic#15]
Hi Jan, I'm wondering, is there a simple way to remove all of the animations based on screen size? Basically anything below 1024px we just want to have the images and no animation. I'm trying to avoid having a separate mobile site. Any help would be much appreciated! Thanks!

**Comment by alycda** [comment]
I appreciate your evaluation of responsibilities for your plugin vs 3rd party animation. I would like to request better clarification within your documentation on your wording: 'reset the pin and tween' to note that tweens created with Velocity, GSAP, etc **will not** be reset by ScrollMagic. 

http://scrollmagic.io/docs/ScrollMagic.Scene.html#destroy

Thanks for the writeup.

**Comment by safareli** [comment]
i use this to disable scrollmagic on small size screens
```js
controller.scrollPos(function () {
  if(window.innerWidth >= 720){
    return window.pageYOffset;
  } else {
    return 0;
  }
});
```

**Comment by ethanmay** [comment]
Here's how I solved this problem, it works really well for me:
``` javascript

jQuery( document ).ready( function($) {

	var tooSmall = false;
	var controller = null;
	var maxWidth = 992; // or whatever your max width is

	if( $(window).width() < maxWidth ) {
		tooSmall = true;
	}

	function initScrollMagic() {
		$('body').scrollTop( 0 );
		controller = new ScrollMagic.Controller();
		// add your ScrollMagic scene goodness here
	}

	if( !tooSmall ) {
		initScrollMagic();
	}

	// part of the problem is that window resizes can trigger multiple times as the events fire rapidly
	// this solution prevents the controller from being initialized/destroyed more than once
	$(window).resize( function() {
		var wWidth = $(window).width();
		if( wWidth < maxWidth ) {
			if( controller !== null && controller !== undefined ) {
				// completely destroy the controller
				controller = controller.destroy( true );
				// if needed, use jQuery to manually remove styles added to DOM elements by GSAP etc. here
			}
		} else if( wWidth >= maxWidth ) {
			if( controller === null || controller === undefined ) {
				// reinitialize ScrollMagic only if it is not already initialized
				initScrollMagic();
			}
		}
	});

});
```

**Comment by blairdow** [comment]
@ethanmay your way worked great for me too (with some slight modifications)! Many thanks :)

```jQuery(document).ready(function($){
    var controller = null;
    
    //set initial values for page width and item height
    var width = $(window).width()
    var subpageHeight = $('.subpage').height()
    var sidebarHeight = $('#consultation-sidebar').height()
    
    function initScrollMagic(){
        $('body').scrollTop( 0 );
        controller = new ScrollMagic.Controller()
        new ScrollMagic.Scene({
            duration: subpageHeight - sidebarHeight,
            offset: 50
        })
        .setPin("#consultation-sidebar") // pins the element for the the scene's duration
        .addTo(controller); // assign the scene to the controller
    }
    
    //767 is my mobile breakpoint
    if( width > 767) {
        initScrollMagic()
    }
    
    $(window).resize(function(){
        //reset values when page size changes
        //my scroll magic is used on multiple pages, duration depends on item heights
        width = $(window).width()
        subpageHeight = $('.subpage').height()
        sidebarHeight = $('#consultation-sidebar').height()
        
        if( width < 768 ) {
            //you can just use 'controller' here as it will return true or false, you dont need all the conditionals
            if (controller) {
                controller = controller.destroy(true)
            }
        } else if ( width > 767 ) {
            //same here 
            if ( !controller ) {
                initScrollMagic()
            }
        }
    })
})
```

**Comment by zucoa** [comment]
@ethanmay This works for me as well, but was curious if when you resize the browser window you too are forced to reload the page in order to get the scenes to reinitialize?

**Comment by ethanmay** [comment]
@zucoa I did experience that occasionally when working in a local development environment. I could not reproduce the behavior once I pushed it live, however.

**Comment by leevh** [comment]
Hope its ok to post in this older issue - I'm having a lot of troubles with this.

- goal: Because scroll effects are different and markup must change between mobile/desktop I need to destroy Scrollmagic, remove inline styles, refactor some markup and reinitialize scrollmagic based on new markup.
- what's happening: Scrollmagic works the first load, but after destroy and reinitialize the tweens aren't changing even though the inline styles are created. Also noticed that the scene indicators keep piling up as you go back and forth.

Code below, which is pretty hacky at the moment as I've been trying everything to debug it.   Hoping someone might have idea whey tweens won't work after reinitialization.

`/**
 * @file
 * Custom scripts for ScrollMagic effects.
 */

/*global ScrollMagic */
/*global TweenMax */
/*global Power0 */
/*global TimelineMax */

(function ($) {

  $(document).ready(function() {

    var controller = null;


    function initializeScrollMagic() {

      $('body').scrollTop( 0 );

      // Init ScrollMagic
      controller = new ScrollMagic.Controller({loglevel:3});

      // Create parallax scene
      $(".page-section--parallax").each(function() {
        var parallax_object = $(this).find(".page-section__bg")[0];
        var text_to_fade = $(this).find(".page-section__content").first()[0];
        // Parallax scene
        new ScrollMagic.Scene({
          triggerElement: this,
          triggerHook: "onEnter",
          duration: "200%"
        })
            .setTween(TweenMax.from(parallax_object,1,{y: '-30%', ease:Power0.easeNone}, 0))
            .addIndicators()
            .addTo(controller);

      });
      console.log('initialize done!');
    }// END initializeScrollMagic




    function destroyScrollMagic(){

      if (controller) {
        controller = controller.destroy(true);

        // Remove any pin-spacers
        $('.scrollmagic-pin-spacer').contents().unwrap();

        //clear all extra inline styles
        $('.page-section__bg').each(function (){
          var $this = $(this);
          var background = $this.css('background-image');

          $this
              .removeAttr('style')
              .css('background-image', background);
        });
        console.log('destroy done!');
      }

    } // END destroyScrollMagic




    function adjustMarkupForLarger(){
      // Restructure the parallax combo box for bigger devices.
      $(".page-section__content__inner > .parallax-combo__content").each(function (){
        $(this).appendTo($(this).closest('.parallax-combo')).addClass("page-section page-section--text-only")
            .wrapInner("<div class='page-section__content__inner'></div>")
            .wrapInner("<div class='page-section__content section-container'></div>");
      });
      $(".parallax-combo .page-section--full-height").each(function (){
        $(this).removeClass("page-section--full-height");
      });
      console.log('adjust for larger done!');
    }

    function adjustMarkupForSmaller(){
      // Restructure (back) the parallax combo box for smaller devices.
      $(".parallax-combo > .parallax-combo__content").each(function (){
        $(this).appendTo($(this).parent().find('.page-section--parallax .page-section__content__inner'))
            .removeClass("page-section page-section--text-only")
            .find('.page-section__content').contents().unwrap()
            .contents().unwrap()
        ;
      });
      $(".parallax-combo .page-section--parallax").each(function (){
        $(this).addClass("page-section--full-height");
      });
      console.log('adjust for smaller done!');
    }


    function mediaSize() {

      if (window.matchMedia('(min-width: 768px)').matches) {

        // Some parallax markup needs changing for larger screen sizes.
        //adjustMarkupForLarger();

        if (!$("body").hasClass("non-mobilejs")) {
          $("body").removeClass("mobilejs").addClass("non-mobilejs");
          destroyScrollMagic();
          setTimeout(function(){
            // doing async stuff
            adjustMarkupForLarger();
          }, 2000);
          setTimeout(function(){
            // doing async stuff
            initializeScrollMagic();
          }, 4000);
        }
      } else {

        // Change back markup if necessary.
        if (!$("body").hasClass("mobilejs")) {
          $("body").removeClass("non-mobilejs").addClass("mobilejs");
          destroyScrollMagic();
          setTimeout(function(){
            // doing async stuff
            adjustMarkupForSmaller();
          }, 2000);
          setTimeout(function(){
            // doing async stuff
            initializeScrollMagic();
          }, 4000);
        }
      }
    }

    mediaSize();

    window.addEventListener('resize', mediaSize, false);


  });

})(jQuery);
`

**Comment by leevh** [comment]
just experimenting, I added 
```javascript
TweenMax.killAll();
```
to my "destroyScrollMagic() function"  above controller.destroy, it gets the reinitialized tweens to move, but their intial values are wrong.
