### ISSUE TITLE
Safari Parallax (demo and real-live code) looks super juggy

### ISSUE THREAD

**Issue by nexflo** [janpaepke/ScrollMagic#167]
http://janpaepke.github.io/ScrollMagic/examples/advanced/parallax_sections.html

Your demo in safari...looks extremly jumpy/jiggy/whizzy or just unsmooth (butter smooth in chrome)

**Comment by ThePath** [comment]
So its all nice and smooth used in that way. But on your demo you just have the backgrounds with no content in the sections. When you are adding elements that you dont want to move with the background into the section container, you have to either absolute position everything or you have to make the div containing your background image absolute and the other content relative so it overlays it. This method produces the jerky/juggy/jitteriness.

Or am I missing something is there an easier way to have the moving background image with content overlayed and have the background image run smooth?

**Comment by janpaepke** [comment]
If you have content in front of the parallax element, you should have it positioned absolutely and put it behind the other content either by DOM order or z-index.
Still to my knowledge moving the element using transformY should be the best aproach.

Please note, that there currently are some jitters reported for the parallax effect, and they are being reviewed: https://github.com/janpaepke/ScrollMagic/issues/256

If you're having trouble with the correct markup for this, please post this as a new issue, linking to a fiddle with the setup as far as you've gotten it.

**Comment by ThePath** [comment]
In your parallax sections demo the background image is positioned relatively. I have recreated your example and it works without jitters but when absolutely positioning the div with background image so to add content in front of it the jitters are quite bad. I will see if I can set up a fiddle.

**Comment by GuenniWeb** [comment]
by the way  a little offtopic but is there a short way to create a scroll effect like on http://www.apple.com/de/macos/sierra/
very nice idea
