### ISSUE TITLE
Elements go past the pin Hook and then bounce back in place

### ISSUE THREAD

**Issue by createlogic** [janpaepke/ScrollMagic#171]
I am facing a strange issue the pinned element actually bypasses the pin and bounces back. If you scroll really slow then it does fine but if you are scrolling at a good pace it would kind of pass through the pin and bounces back to its position.

Please find the link below where actually the issue is happening. If you scroll to from intro to fact01 and continue though the facts the issue can be seen.

Please below is the link of the actual implementation:

http://www.digitaslbiacademy.com/demo/madinat/

Regards,
Bilal

**Comment by karneaud** [comment]
Did you guys ever fixed this?

**Comment by dirtyhenry** [comment]
I can reproduce this behavior on a work-in-progress project. 
I tried to set up a little jsfiddle to reproduce it: http://jsfiddle.net/rgz8ey7w/11/

But... The fiddle can't reproduce it.

I suspect this has to do with the fact I stripped the code down to its core which leads me to think that elements going past the hook are linked with a performance issue of browsers.
