### ISSUE TITLE
Custom dependency / complete independency of Scroll Magic is needed

### ISSUE THREAD

**Issue by sakshamsaxena** [janpaepke/ScrollMagic#190]
I've tried using TweenLite along with a few packages instead of TweenMax but ScrollMagic won't work then. Even jQuery is seemingly a formaility, since GSAP-JS doesn't really require it. It's a pity seeing TweenMax's staggering powers being simply wasted when we don't really need it all of it.

We can either :
1. Bundle the essential dependencies in the core build, which won't really hurt even in development version.
2. Bundle the essential dependencies in a separate .js to be used alongside ScrollMagic.

I haven't yet gone through the source code yet, but will try to update on this issue as soon as I can.

**Comment by janpaepke** [comment]
FYI: https://github.com/janpaepke/ScrollMagic/releases/tag/v2.0.0-alpha
