### ISSUE TITLE
More documentation/examples for mobile?

### ISSUE THREAD

**Issue by dkrause10** [janpaepke/ScrollMagic#20]
Hi Jan, I'm having a hard time getting anything to work right on mobile. When I don't use the container method, I can at least get animations to work but not correctly. When I use the container method, nothing happens. No animations, no errors. I'm sure that I'm doing something wrong but can't figure out what. I basically copied what you had in your "Mobile Advanced" example. Is there specific CSS that is necessary for this to work? Do you have any other examples, maybe with multiple animations and/or pins? Thanks in advance for any help you can provide!

**Comment by clemon** [comment]
thank you @yaronguez ! :)
