### ISSUE TITLE
ScrollMagic + scrollto + Mac Safari (Retina?) issue

### ISSUE THREAD

**Issue by johnfmorton** [janpaepke/ScrollMagic#210]
I've seen a particular issue when using ScrollMagic to create parallax animation and also using global navigation to go to particular points on the page. I'm mid development and don't have a code sample to share yet, but 2 "live" examples of this inconsistent behavior are sites referenced on the ScrollMagic home page:

http://www.lempens-design.com/
http://www.viko.net/en/

Using http://www.lempens-design.com/ as the example, when I open this URL on a retina MacBook Pro (brand new machine, OS X 10.10.1, Safari 8.0) and click "Contact" from the global navigation, the page does not always make it to the appropriate area of the page. On occasion, I will see this on a non-retina display when using Safari 8 / OS X 10.10.1, but the problem seems more pronounced on a retina display Mac. I do not see this issue when using Chrome, so I think it's some issue with Safari. 

I've been doing tests to try to isolate the issue, and when I'm using GSAP alone, I never see the issue. I've got a CodePen built as a test here: http://codepen.io/johnfmorton/pen/jEqMqK . This does not have ScrollMagic in it yet and the _scrollto_ function in TweenMax executes like I expect. 

sample of what I mean by _scrollto_:

`TweenMax.to(window, 2, {scrollTo:{ y:$('#about').offset().top }, ease:Power2.easeOut });`

Any thoughts on what's going on with this scenario with MacPro + Safari 8 + retina displays + ScrollMagic + scrollto?

**Comment by johnfmorton** [comment]
After some additional work on the project that instigated my initial post, I kept working on this issue. It turns out the "autoKill: false" *did not* fix the issue as I thought. 

My next solution was to drop the Greensock "scrollTo" plug in entirely and try to use the jQuery version, which would look something like this:

```
$('html, body').animate({ scrollTop: '1000px' }, {
                duration: 1000,
                complete : function(){
                    // alert('This alert will popup twice. Once for html and once for body.');
                }
            }
        );
```

Unfortunately, this jQuery solution also exhibits similar problems in Safari (version 8.0.3 as I write this). The scrolling action does take place and seems to get to the target *most of the time*, but even when it does the animation while the window scrolls, it is jittery as moves into position. 

I **do not** see this jittery animation in Chrome, Firefox or the new Vivaldi browser.

The conclusion I draw from this is that there is no specific problem in ScrollMagic, Greensock's "scrollto" plugin, or even in the jQuery animate scrollTop method. This is a bug in Safari as far as I can tell.

**Comment by janpaepke** [comment]
Okay, thanks for letting me know...
If you have some time left you could check out the latest [dev build of ScrollMagic 2.0](https://github.com/janpaepke/ScrollMagic/tree/development) and check if the problems persist.

**Comment by Paulimausi** [comment]
I, too, had problems with smooth scrolling in Safari. After having read this issue I looked into the issue and indeed found that in Safari sometimes unwarranted scroll events get triggered. Fortunately those events have the scrollDirection "PAUSED".
As a workaround I use a condition such as the following and I haven't had the problem since.
````javaScript
.on
(
	"enter leave", function( e )
	{
		if (e.scrollDirection != "PAUSED")
		{
			yourTween()
		}
	}
)
````

**Comment by izumskee** [comment]
Hello, guys! 
I have the same problem too.
Is it fixed now?
Can you tell me any suggestions how to fix it?

**Comment by jyeg** [comment]
what's going on with this?

**Comment by maryrnd** [comment]
Good afternoon!
The problem is that the image doesn't open in Safari MacBook Pro and Air, which should be with the scroll animation...
On other devices that use Safari, there are no problems..
