### ISSUE TITLE
Apply same scene to every element with same class

### ISSUE THREAD

**Issue by CalebEverett** [janpaepke/ScrollMagic#215]
Hi,

I have many instances of bold text in my document with `<strong>` tags that I put a class of .animated into. I'd like to have the text be normal until it gets to the middle of the window and then turn bold. I looked at the examples in 52 and 100, but couldn't get it working the right way. 

``` js
var strongOrigin = {
    opacity: 0,
    scale: 0
}

var strongTween = TweenMax.staggerFrom($(this), 0.5, strongOrigin);

$('.animated').each(function(){
  var controller = new ScrollMagic();
  var strongScene = new ScrollScene({duration: 100,triggerElement: $(this),offset: -100})
      .setTween(strongTween)
      .addTo(controller);
});    
```

Thanks for taking a look.

**Comment by janpaepke** [comment]
Yes that is exactly how you would approach this. :)
