### ISSUE TITLE
How to animate on page load?

### ISSUE THREAD

**Issue by chrisberthe** [janpaepke/ScrollMagic#221]
What would be the best way, if possible, to animate an element on page load?

Using the SVG drawing as an example, would I have to set the start point at 0px and spoof the animation using something like scrollTo (until the end point)?

**Comment by janpaepke** [comment]
Hi Chris,
that very much depends on what you are trying to achieve.
If you just want the animation to run once, without reversing it, you can just do that without ScrollMagic, just using GSAP (as in the example).
If you want the animation to be reversable depending on scroll position you will need to link it using ScrollMagic.
Should the animation be scroll-bound, then yes, you need to animate the scroll, as you assumed. (btw.: start point 0 is just a scene with neither an offset, nor a trigger).

If you want the animation to run independently of scroll position, but reverse, once the user scrolls all the way back up, there are again two possible solutions:
1. custom way: make a scene at the beginning and use event listeners to manually call `tween.reverse()` on your animation
2. ScrollMagic way: make a zero duration scene at `offset: 1` that triggers the animation. Also add another scene at `offset: 0` with a duration of 1, that pins the start viewport. Then jump to page scroll pos 1 on load.

Does this answer your question?

**Comment by chrisberthe** [comment]
Definitely - thanks for the breakdown Jan.

**Comment by janpaepke** [comment]
Just because I stumbled over it today: Check here for an example of scroll bound auto play: http://poppyspend.britishlegion.org.uk

**Comment by chrisberthe** [comment]
Awesome! Just what I was looking for, thanks.

**Comment by JoeOP** [comment]
2. ScrollMagic way: make a zero duration scene at offset: 1 that triggers the animation. Also add another scene at offset: 0 with a duration of 1, that pins the start viewport. Then jump to page scroll pos 1 on load.

Any chance I could snag a quick example of this?
