### ISSUE TITLE
Start scene right in the beginning viewport area of the scroll container

### ISSUE THREAD

**Issue by funkybudda** [janpaepke/ScrollMagic#222]
hello all,

this might be a newbie question, is there anyway to trigger a scroll scene animation when the scene is right at the beginning of the scroll container? I have tried all the trigger hook options, and even set the duration to 0, but the scene is not triggered.

**Comment by janpaepke** [comment]
Hi!
Have a look at the [scene manipulation example](http://janpaepke.github.io/ScrollMagic/examples/basic/scene_manipulation.html) to get a better idea of how the various options influence the scene.
Change the values in the form on the left and watch the indicators on the right change.
`triggerHook` -> defines where in relation to the container the scene should be triggered
`triggerElement` -> when set this element must pass the `triggerHook` for the scene to be triggered
`offset` -> a numerical offset at which the scene is triggered. If a `triggerElement` is defined, it will be added to its position.

hope this helps.

**Comment by funkybudda** [comment]
hi,

yes I have played around with the  scene manipulation example, so perhaps I need to better explain what i am trying to achieve... 

Using the scene manipulation example, the landing text in the center when u go the page (the "Scene Manipulation" text in bold), if I want to animate them, how could I do so if I set the trigger point to 0.5? All the examples required scrolling certain area to start the first animation, is there a force trigger if you want toe animation to start right in the beginning of the viewport area? As I pointed out above, I have tried setting the trigger element in px value to be near, above or below the trigger hook location, but cant get the animation to show. If I move the trigger element further down, then it works.

**Comment by johnfmorton** [comment]
Stepping in to see if I can give any help here. In my use of ScrollMagic I start a scene that is triggered at the very top of the viewable area on a page like this:

	// Get window size
	winH = $window.height();
	window.myScene = new ScrollScene({ triggerElement: "#firstBlock", duration: winH, triggerHook: 0, offset: 0})
		.setTween(videoTween)
		.addTo(controller);
	// show indicators (requires debug extension)
	myScene.addIndicators({
		suffix: 'myFirstScene'
	});

In my HTML, the div with an ID of "firstBlock" is at the very top of the viewport in my window. 

Does that help?

**Comment by janpaepke** [comment]
@funkybudda John's example is correct.

But let me simplify it even more for you:
If you create a scene, that has __neither a trigger element, nor an offset__, its start position will resolve to a scroll position of 0, so right at the beginning.
This is independent of the `triggerHook` setting.
You can check in the scene manipulation example by removing the "#trigger" from the triggerElement box and then clicking update.

This should clear things up, right?

**Comment by funkybudda** [comment]
@janpaepke and @johnfmorton,

sorry for the delay reply due to a severe cold, but what you guys wrote really helped my situation. I was under the impression that every scene always require a trigger-hook and I have resolved my issue.

thanks for the help.
