### ISSUE TITLE
trouble with reverse [how to timeLine.seek(0) on scrollMagic reverse]

### ISSUE THREAD

**Issue by dimamovcean** [janpaepke/ScrollMagic#223]
Hello
http://jsfiddle.net/0gnev9h6/
this is what im trying to do.
when i scroll down action starts - it's OK
but when im scrolling up i need to reset my tween to 0

trouble is when scrolling down second time, action delays for unknown period and then starts

thank you

**Comment by janpaepke** [comment]
Hi,

in short: Either leave GSAP playback control to ScrollMagic, or do it manually.
But don't do both.
Here's a solution for manual control: http://jsfiddle.net/0gnev9h6/2/

let me know if that clears things up.

regards,
J

**Comment by dimamovcean** [comment]
works perfect
http://jsfiddle.net/0gnev9h6/3/
thank you very much!!!!

**Comment by janpaepke** [comment]
Glad I could help.
