### ISSUE TITLE
WordPress > Scrollmagic > with main menu link to section of homepage

### ISSUE THREAD

**Issue by benjino** [janpaepke/ScrollMagic#229]
I can understand the anchor link usage of scrollmagic…

https://janpaepke.github.io/ScrollMagic/examples/advanced/anchor_link_scrolling.html

…but can't figure out how to have the same effect as it in WordPress to have a Main Menu link trigger to a target down the homepage?

The only ID for the page section is the div id for the post. I can get the same effect by using 'mydomain.com/#featured-post-x' but it makes the main menu link have :active state styling. While this gets around using scrollmagic altogether the :active state styling isn't desired. If I use just '#featured-post-x' in the custom link of Menus it works but only when you're on the homepage. I want to be able to have the effect no matter what page you're navigating from.

**Comment by janpaepke** [comment]
Hi @benjino 

I'm  having a very hard time understanding what your problem actually is.
Can you try to explain it a little better and maybe provide an example?

**Comment by krnlde** [comment]
I don't get you problem either. So you probably mean something like http://getbootstrap.com/javascript/#scrollspy

**Comment by benjino** [comment]
No its scrollspy isnt the answer. Let me explain again. The homepage is fairly long with a few sections. I simply want a top nav (main menu) link to trigger going to a section down the page on the homepage, in WordPress.

**Comment by krnlde** [comment]
Do these sections (posts) already provide IDs? If yes you can use any lib you want, like jquery to achieve this. `$('HTML, body').animate({scrollTop: $('#yourId').offset().top});`

**Comment by benjino** [comment]
Well the section has a class, and the post has an ID. The section is probably the ideal area to target. If you target the post id it will land a bit below the section. So I guess I would use the ID and offset it to land where I want?

**Comment by benjino** [comment]
Alright, thanks. I see my theme has scrollTo in its js directory. I just need to figure out the right link to put into the custom menu link in Menus of WordPress

**Comment by janpaepke** [comment]
[closing due to no relation to ScrollMagic and resolved otherwise]
