### ISSUE TITLE
ScrollTo Effect

### ISSUE THREAD

**Issue by street223** [janpaepke/ScrollMagic#230]
Hi,

i really enjoy scrollmagic, but I have a small problem and I don't know how to fix it.

Here is the jsfiddle link:
http://jsfiddle.net/ut6mt3ub/21/

And that's what I like to do:
http://codepen.io/bassta/pen/kDvmC

I'm new to scrollmagic and try to make this since some hours. It would be really nice If someone could help me.

Thanks

**Comment by janpaepke** [comment]
Hi Street,
ScrollMagic is a scroll interaction plugin, not a onepage-scroll plugin.
To achieve that I would recommend [fullPage](http://alvarotrigo.com/fullPage/) or [OnePageScroll](http://www.thepetedesign.com/demos/onepage_scroll_demo.html).
Hope this helps,
J

**Comment by street223** [comment]
Hi Jan,

thanks! That was what I'm looking for.

I think I will use a combination of both.

Regards

**Comment by janpaepke** [comment]
I hope you mean a combination of ScrollMagic and fullPage or OnePageScroll, not a combination of fullPage and OnePageScroll? :)
This might also be of interest to you: https://github.com/janpaepke/ScrollMagic/issues/220#issuecomment-70084198

regards,
J

**Comment by street223** [comment]
Sorry, yes that's what I mean. I will try to use a combination of ScrollMagic and fullPage.

Thanks for the link to the comment I've read it and there is one last question. It's possible to use the pin function of ScrollMagic with fullPage?

Regards

**Comment by janpaepke** [comment]
Yes it is, as long as you disable the css transform option of fullpage, as described in the other post.
This is due to this problem: https://github.com/janpaepke/ScrollMagic/issues/178
