### ISSUE TITLE
Bootstrap Carousel issue on tablets

### ISSUE THREAD

**Issue by katquinto** [janpaepke/ScrollMagic#238]
Hello @janpaepke,

I just like to ask you if you have encountered any issues integrating bootstrap carousel on scrollmagic. When I run it on tablets and click on next or prev button for slide transition, The scrolling goes back to the very top. Thanks for your help. Really cool library BTW!!! :+1: 

Thanks,
Kat

**Comment by janpaepke** [comment]
Hi Kat,
glad you enjoy the plugin.
so far there have not been any issues I am aware of.
Please make sure this is a ScrollMagic related issue by removing it from the code and then checking if the issue still occurs. If yes it must be something else. :)

(to be honest if I had to guess the buttons probably have an empty anchor link sending the page back to start. Also: definitely check your console for errors.)

**Comment by katquinto** [comment]
Hello @janpaepke, you are right, it's an empty anchor link that causes the issue. Thanks again :-) :+1:
