### ISSUE TITLE
Pin and Tween Function -> broken scroll/visuals

### ISSUE THREAD

**Issue by Jebiz** [janpaepke/ScrollMagic#243]
Hi,
i use the setPin() and other Tween-Options on one Site. It all worked perfectly in Chrome. But in other Browser (Safari, ...) the visual representation gets totally broken after intense scrolling. The Divs which normally fades in/out just there at 100% on different spot and things like that.

I can't post any code at the moment. But is there any known problem with intense scrolling, or Problems with many pin/tween functions in safari/firefox?

Thanks for you help ;)

**Comment by janpaepke** [comment]
Hi Jebiz,
There are none of these issues I know of.
The only thing I could think of is the overwrite phenomenon, which occurs when tweening the same property on an object multiple times (like fading in and out) and scrolling very fast.
This should be something your console warns you about, though, if you use the latest GSAP version.
It should redirect you to the WIKI, where it explains this in more detail.

I would also ask you to read it and find out if this might be what's causing your problem: https://github.com/janpaepke/ScrollMagic/wiki/WARNING:-tween-was-overwritten-by-another

If it isn't please try to make a fiddle or codepen showcasing your issue for us to be able to help you further.
Either way, let us know what you find out.

**Comment by janpaepke** [comment]
any updates?

**Comment by janpaepke** [comment]
[closed due to inactivity]
