### ISSUE TITLE
Z-index interactions with scrollbar

### ISSUE THREAD

**Issue by wmodes** [janpaepke/ScrollMagic#246]
Jan, I am creating a horizontally scrolling site with pinned elements. When the scrollbar is scrolling the body, I have no problems. But when I instead scroll a #doc div just inside the body, all of the triggers still function perfectly, but there is a strange visual artifact. Namely, the scrollbar disappears when elements are scrolling, then reappears when they are pinned.

When I set the z-index of the #doc div, the scrollbar didn't disappear, but the element did when it was pinned.

Is this too weird to diagnose without viewing the app?  It isn't deployed yet, so I can't show you yet.

**Comment by krnlde** [comment]
Hey @wmodes, can you provide an isolated jsfiddle so we can see the problem? We don't actually need the full app (unless the error is located in the app itself).

**Comment by janpaepke** [comment]
Sorry for the delayed answer, I was on holidays...
I would agree with @krnlde though. If possible please provide a jsfiddle.

**Comment by wmodes** [comment]
Here is a [jsfiddle](https://jsfiddle.net/ht32m6kr/1/) that demonstrates the problem. On my site, I worked around it by fiddling with containers, but this demonstrates what is happening.  When you scroll horizontally, the moment the div is pinned, you lose the scrollbar.

**Comment by janpaepke** [comment]
mh. I tried on chrome, safari and firefox. the scrollbar doesn't disappear.
I do have a guess though why this might be happening to you.
It might be the same thing that is happening in this issue: https://github.com/janpaepke/ScrollMagic/issues/244

And as I pointed out in the [solution]():
> [...] fixed images are attached to the body and thus have a higher z-index than their parents.
So the image basically covers the scrollbar.

So if your image is exceeding the bounds of the content of the div, it will overlap the scrollbar.
The solution I can think of here is to either make sure the bounds of the pinned element don't exceed the scroll div, or add a class to the pinned element during pin to correct for this.

hope this helps.

**Comment by wmodes** [comment]
Possibly the way I handled it was a liberal application of `overflow: hidden`

**Comment by janpaepke** [comment]
so can this be considered resolved?

**Comment by janpaepke** [comment]
[closed due to inactivity]
