### ISSUE TITLE
Tweens are widening page

### ISSUE THREAD

**Issue by bbogin** [janpaepke/ScrollMagic#248]
Hello,

I am using scrollmagic and I want to tween objects onto the page from the left and right. As I have it set up right now, the tweens are widening the screen, allowing a user to see them if they scroll to the right.

Here is the address of my live website: bbogin.com. The source, if you view source, is pretty clean, but the tweens that I'm looking at specifically are tween, tween2, and tween3 in script.js:

```JavaScript

tween = TweenMax.fromTo("#bio", 1, 
		{"right": "-336px"},
		{"right": "100px"}
	);

	var scene2 = new ScrollScene({
		triggerElement: "#background", 
		duration: 325
	}).setTween(tween)
	.addTo(controller);


	var xtrans = (width)/2-300-25

	tween2 = TweenMax.fromTo("#major", 1, 
		{"left": "-300px"},
		{"left": xtrans+"px"}
	);

	var scene3 = new ScrollScene({
		triggerElement: "#work", 
		duration: 325
	}).setTween(tween2)
	.addTo(controller);

	tween3 = TweenMax.fromTo("#cast", 1, 
		{"right": "-300px"},
		{"right": xtrans+"px"}
	);

	var scene4 = new ScrollScene({
		triggerElement: "#work", 
		duration: 325
	}).setTween(tween3)
	.addTo(controller);

```

**Comment by krnlde** [comment]
Set `body {overflow-x: hidden;}`

**Comment by bbogin** [comment]
Thanks! That did it.

**Comment by krnlde** [comment]
Glad that helped :) 
Would you mind closing this issue yourself? 

Greets
