### ISSUE TITLE
Unsure how to scroll full-size windows and pin them

### ISSUE THREAD

**Issue by reduxdj** [janpaepke/ScrollMagic#25]
I was trying to scroll a div (for the last 14 hours :/). I am unable how to use scrollmagic to tween and pin a fullscreen div. For instance, each view is a background image with the width set to 100% and height is dynamically sized - the image is full width using background cover. For instance, what trigger element do I use to trigger these elements? If each view is has it's own scene, and each view has it's own controller, and basically the first image, I want to pin immediately - how do I go about doing this? I was using the trigger as the container view itself, but then when I went to pin the elements top position changed, making it go off the screen.  I tried setting offset, with no real success either.

I know this probably isn't clear, but I'm not sure from the examples how to achieve this.

Thanks

**Comment by nickensoul** [comment]
@shumuko did you resolve an zero-height trouble?
