### ISSUE TITLE
Update to 2.0.0

### ISSUE THREAD

**Issue by wmodes** [janpaepke/ScrollMagic#250]
Any chance of a meteor packaged version of ScrollMagic 2.0.0?

**Comment by krnlde** [comment]
For now @janpaepke supports bower and npm as package manager. I personally don't see the advantage and necessity of diverging into other and less popular managers.

**Comment by wmodes** [comment]
Have you tried installing the current version? I couldn't get it to work, and so figured there was some magic you did to get it to work with meteor.

**Comment by janpaepke** [comment]
To be honest I hadn't even heard of meteor, had to look it up.
Answering your question in short: There are currently no plans to create a meteor package.
As meteor gets more popular and demand rises (if anyone reads this, please voice your desire below), we might reconsider.
Or someone else might publish SM as a meteor package...

**Comment by wmodes** [comment]
@krnlde, Is it possible to install SM successfully with bower or npm on meteor? If so, what is the process? I'd love to upgrade to 2.0.0. 

@janpaepke, generally meteor fans bundle up their fave packages as meteor "smart packages." However, they rapidly fall behind the development of the original package leaving us stuck with older versions, which doesn't feel very smart to me. I like meteor so far, but this aspect I am not stoked about.

**Comment by krnlde** [comment]
@wmodes I don't know. Never worked with meteor. Feel free to try it and give feedback :)

**Comment by wmodes** [comment]
Beyond my capabilities.

**Comment by janpaepke** [comment]
Check this out, girls. :)
https://github.com/hipstersmoothie/Meteor-ScrollMagic

**Comment by wmodes** [comment]
Wow, thanks, Jan.
