### ISSUE TITLE
Scroll Magic in mobiles

### ISSUE THREAD

**Issue by sankukai** [janpaepke/ScrollMagic#257]
Hello,
First of all, I am a beginner with ScrollMagic.
I found one web site to guide my first steps into the world of ScrollMagic but at the end of an article,
they warn (and I quote) : " ScrollMagic works great for Desktop animations but doesn’t translate to iOS. You’ll want to disable your scroll animations on iPad and iPhone because of the way Mobile Safari delays animations until after the user has finished scrolling. "
However, I have seen on the documentation of ScrollMagic, that there is "mobile compatibility" ...
How comes ? Is it because of an update from ScrollMagic ? 
Or do you think the warning of the article I have found was a little wrong ?
Thank you very much to give me an answer :-) 
San

**Comment by krnlde** [comment]
You'll have to use `iScroll` for smooth scrolling behaviour. See http://janpaepke.github.io/ScrollMagic/examples/expert/mobile_advanced.html

**Comment by janpaepke** [comment]
Also please post a link to the article, so we could set the record straight.
ScrollMagic explicitly tries to support mobile, although in some cases it might be wisest to disable it for performance reasons.
