### ISSUE TITLE
Scrolling in different directions

### ISSUE THREAD

**Issue by lizzy-creative-covered** [janpaepke/ScrollMagic#258]
Hi,

I'm looking to create two columns that scroll in different directions, so as you scroll, the left column goes up and the right column goes down.

I can see this was investigated here but the examples no longer work:
https://github.com/janpaepke/ScrollMagic/issues/214

Thanks

**Comment by krnlde** [comment]
Just fix the paths to all the external resources in the fiddles and have a look again. They're pointing to 404s right now.

**Comment by janpaepke** [comment]
I updated the fiddles in https://github.com/janpaepke/ScrollMagic/issues/214 . 
Does this solve your issue?

**Comment by lizzy-creative-covered** [comment]
Yes this example is now working again thanks.

I'm trying to add extra items to each column, but want the left column to continue scrolling in the opposite direction no matter how many items are added to either column?

http://jsfiddle.net/bbwgj78u/

**Comment by janpaepke** [comment]
Just add them to _both_ columns and change the duration and movement distance accordingly...
http://jsfiddle.net/bbwgj78u/1/

**Comment by janpaepke** [comment]
@lizzy-creative-covered does this solve your issue?

**Comment by lizzy-creative-covered** [comment]
That works perfectly thanks.

I'm just wondering if there's a way to almost snap/lock each section as it scrolls, and if you stop in the middle of a section it will snap to the top?

**Comment by janpaepke** [comment]
it is but this would fall under the category of "scrolljacking".
Personally I am against everything that takes away scroll control from the user, which this would.

This would also be something that would need to happen outside of ScrollMagic.

So I'm closing this now, as all ScrollMagic related issues seem to be resolved. :)
