### ISSUE TITLE
Anchor Link Scrolling

### ISSUE THREAD

**Issue by foxdust** [janpaepke/ScrollMagic#259]
Hi,
I saw the example on anchor link scrolling but I am a little confused on how to do that using one scrollscene/timelinemax. 
For example, my code is set up like this:

var tween1 = TweenMax.to("#frame1", 1, {width: "100%", delay: 0.6});
var tween2 = TweenMax.to("#cover .fade", 1, { opacity: '1', delay: 0.6});
var tween3 = TweenMax.to("#frame2", 1, {width: "100%", delay: 0.6});
var tween4 = TweenMax.to("#cover .fade", 1, { opacity: '1', delay: 0.6});

var pinAnimation = new TimelineMax()
        // frame 1
        .add([tween1, tween2])
        // frame 2
        .add([tween3, tween4])
     
var scene = new ScrollScene({
        triggerElement: "section#pin",
        duration: 2000
})
       .setTween(pinAnimation)
       .setPin("section#pin")
       .addTo(controller);

How can I get an anchor link for each frame?

**Comment by janpaepke** [comment]
Well you'll need to determine where exactly frame2 starts.
Since the animations in both frames both last for one second this would mean they are at 50% of the scene duration, so the correct scroll offset should be these:
```js
var offsetFrame1 = scene.scrollOffset();
var offsetFrame2 = offsetFrame1 + (scene.duration() / 2);
```

hope this helps?

**Comment by janpaepke** [comment]
@foxdust did this solve your issue?

**Comment by foxdust** [comment]
Yes, it did :) Thanks a lot!

**Comment by janpaepke** [comment]
you're welcome.
