### ISSUE TITLE
Possible source causing jitter and other weird scroll artefacts in Safari.

### ISSUE THREAD

**Issue by pthag** [janpaepke/ScrollMagic#261]
I was testing a lot with ScrollMagic 2.0 and found out that it was make sort of chucky steps in the animations that where scroller controlled. Few people made complaints about it.

Funny thing is. I found out, my Mac with a logitec mouse which has steps in its wheel makes the animations go in chucky. When I use an Apple mouse or trackpad which doesn't have any physical steps in it. Everything goes smooth. 

I also saw that scrollmagic was programmed by following the ticks for performance, may this all is related?

**Comment by pthag** [comment]
And next to that, if you grab the scrollbar to scroll everything goes smooth as well.

**Comment by pthag** [comment]
Ok this was not the case, just incorrect usage of the script me me, sorry!

**Comment by janpaepke** [comment]
This was probably also related to: https://github.com/janpaepke/ScrollMagic/issues/255#issuecomment-82322149
