### ISSUE TITLE
3D transforms and trigger position

### ISSUE THREAD

**Issue by Paulimausi** [janpaepke/ScrollMagic#262]
I want to create a paper fold animation. Using GSAP I use the rotationX transform to fold divs upward.

The problem is: When ScrollMagic calculates trigger positions it factors in the 3d transform.
Now if there is a trigger element on a div that is folded up (e.g. rotationX: -180) the trigger position is moved up.

Is there a way to make the trigger position of an element not factor in 3d transforms so it won't get triggered if the container div is rotated upwards?

**Comment by janpaepke** [comment]
Hi there!
There's two possible solutions for this:
1.) Don't use your animation target as a trigger element. Instead create an absolutely positioned element at the exact same (original) position. It will remain there and so will the trigger position.
2.) Don't use a trigger element in the first place. Simply use an offset.

Hope this helps.

**Comment by Paulimausi** [comment]
Thanks for the tips. I am working on a workaround, possibly with a conditioned trigger.

**Comment by janpaepke** [comment]
please report back, so we can close this issue if you are able to resolve it.
:)

**Comment by Paulimausi** [comment]
As you have pointed out there are various ways to avoid the problem. I was able to find a workaround. Thanks!

**Comment by janpaepke** [comment]
glad I could help.
