### ISSUE TITLE
Change Panel As Div Wipes Over

### ISSUE THREAD

**Issue by bbogin** [janpaepke/ScrollMagic#263]
Hello,

I love scrollmagic but I'm struggling to figure out how to achieve what I'm trying to get. I want to have a panel in the background, and a div that's maybe 20% height and 100% width. As the user scrolls, I want to wipe in the next panel, as if it were behind the whole time. 

It's a lot like this website: https://www.tinkapp.com/en/ in the middle section, but instead of the parallax effect, I just want the background images to stay in the same place, and I want the background images to be the height of the page.

Am I being clear enough?

Do you mind helping me?

Thanks,
Ben

**Comment by janpaepke** [comment]
Hi Ben,
If the background should stay in the same place then you might not need ScrollMagic at all.
Simply create a div layer with the size of the viewport, set it to `position: fixed` and use `z-index` to put it behind your 20% div.
Something like this: http://jsfiddle.net/4oones5x/

Or is this not what you were going for?

**Comment by bbogin** [comment]
Hi Jan,

This is what I'm going for, except I would like a different panel to be
revealed as the div scrolls up. A lot like the parallax sections part of
the scrollmagic examples. Except for I don't need any parallax, I just want
the effect of "content 1" revealing the second section as it scrolls up.

Thanks for your response,
Ben

**Comment by janpaepke** [comment]
Well in this case you indeed do need ScrollMagic.
Create a second background and hide it.
Then create a tween that reveals it and attach that to a scene.

If you do it right, it looks like this: http://jsfiddle.net/janpaepke/ej22d9w1/

this should be it, right?

**Comment by bbogin** [comment]
That JSfiddle doesn't seem to work for me (it loads, but no tween) but I
understand it, and hopefully I can get it working on my computer.

Thanks,
Ben

**Comment by janpaepke** [comment]
It loads fine for me.
The tween is what reveals the dog image, when u scroll down.
Are you sure it doesn't work?

**Comment by bbogin** [comment]
Got it, thanks so much.

Ben

**Comment by janpaepke** [comment]
all right. glad I could help.
