### ISSUE TITLE
Parallax mobile & anchor scroll

### ISSUE THREAD

**Issue by tenfiftysix** [janpaepke/ScrollMagic#265]
I am creating a site and do not want the parallax script file to run when people are on from their tablets or phones (so under 991px). Is there a way I can disable the parallax file once the width is smaller than that size? If you could go into as much detail on how to do it, that would be great because I am not that familiar with javascript.

Second issue. Is there a way to make the anchor scrolling work with parallax? I have attempted to do it, but it doesn't scroll. Maybe I am putting the code in wrong, but I want to find out if it's possible before I spend hours on it. 

Also, I still want the anchor scrolling to work while people are viewing on mobile. I hope that's possible? 

Thanks!

**Comment by janpaepke** [comment]
Hi There!

In the [support guidelines](https://github.com/janpaepke/ScrollMagic/blob/master/CONTRIBUTING.md#support-guidelines) it clearly states that you should only put in one issue per post.
This makes it a lot more manageable and easier for other people to find solutions.

It also says that you should use the search before posting.
Had you done so you might have found these posts:
https://github.com/janpaepke/ScrollMagic/issues/117
https://github.com/janpaepke/ScrollMagic/issues/75
https://github.com/janpaepke/ScrollMagic/issues/15

And still the answer is this:
```js
$(window).on("resize", function(e) {
  if ($(window).width() < 769 && controller.enabled()) {
    controller.enabled(false);
  } else if (!controller.enabled()) {
    controller.enabled(true);
  }
});
```

Regarding your second question:
Anchor scrolling and parallax are totally independent from one another.
So yes it should work and yes it should also work when it's disabled on mobile.

**Comment by janpaepke** [comment]
does this answer your question?
