### ISSUE TITLE
IE pin scrolling issues

### ISSUE THREAD

**Issue by katquinto** [janpaepke/ScrollMagic#267]
When using pin on IE, screen jumps up and down upon scrolling. Is there any work around for this?

**Comment by janpaepke** [comment]
please provide a fiddle to reproduce this.

**Comment by katquinto** [comment]
Hello jan,

This is the website we are developing http://mistral02.smb-hexagroup.com/.

Thanks,
Kat

**Comment by janpaepke** [comment]
Is this a permanent link?
Please make sure this link will be available even after this issue is closed, as per our [support guidelines](https://github.com/janpaepke/ScrollMagic/blob/master/CONTRIBUTING.md#support-guidelines).

I tested this on a virtual machine and the only think I could notice is that the text at the beginning seems to jump up a little before it goes back to the middle.

Is this what you  mean?

**Comment by katquinto** [comment]
Hello Jan,

No worries. This is a permanent link. Well, on IE, in some of machines, we noticed when user scrolls down, the page is wiggling/jumping. I think also, depending on the mouse you are using. Does scrolling response based on the mouse? Also, I was thinking, I have placed several animations on that page. Maybe IE cannot handle those animations (just wondering)?

Thanks Again! :+1:

**Comment by janpaepke** [comment]
On FF and IE possibly resolved in https://github.com/janpaepke/ScrollMagic/issues/255#issuecomment-82322149.
Issue remains in Safari.

Confirmations?

**Comment by GitHubish** [comment]
I have the same problem (i use scrollmagic 2.0.2) :(

**Comment by janpaepke** [comment]
Consolidated into https://github.com/janpaepke/ScrollMagic/issues/288

**Comment by bcato3000** [comment]
I'm experiencing the exact same problem and IE...

http://cato3000.com/AllegisGroup/_html/vertical-carousel.html

I can't find any real answers here: [#255 (comment)](https://github.com/janpaepke/ScrollMagic/issues/255#issuecomment-82322149) or here: [#288](https://github.com/janpaepke/ScrollMagic/issues/288)

Also, katquinto's link still isn't working in IE when I checked too, leading me to believe that it has not yet been fixed? http://mistral02.smb-hexagroup.com/

Can you please help???
