### ISSUE TITLE
ScrollMagic 2.0.1 scrollDirection "PAUSED" when page is scrolled

### ISSUE THREAD

**Issue by Paulimausi** [janpaepke/ScrollMagic#271]
Since v2.0.1 I get problems with the scrollDirection. If I scroll using scroll bars or sometimes even with my mouse wheel the scrollDirection is always "PAUSED" instead of "FORWARD" or "REVERSE".
That is not happening with v2.0.0.
I am on a Mac and have tested it with Safari, Mozilla, Chrome.

**Comment by janpaepke** [comment]
bug confirmed. will be fixed.

**Comment by Paulimausi** [comment]
I am still getting only "PAUSED" events in Safari v8.0.4 and Chrome v41.0.2272.89.
It works in Firefox.

**Comment by VamshiKrishnaZL** [comment]
No "start" & "end" event callbacks are fired on IE, Safari, Chrome.

**Comment by janpaepke** [comment]
@Paulimausi This fix is not released yet. It will be in the next release.
@VamshiKrishnaZL I can *not* confirm this.
I tested using http://janpaepke.github.io/ScrollMagic/examples/basic/custom_actions.html
The "last hit" value wouldn't change if `start` or `end` were not triggered.
If you have a different usecase to reproduce, please provide a jsfiddle and post as new issue.

**Comment by Paulimausi** [comment]
Cool! Thanks very much!

**Comment by VamshiKrishnaZL** [comment]
Yeah, the callbacks are fired but getting only 'PAUSED' events. Sorry for that. Waiting for the next release. Thank you!

**Comment by hbwoodrose** [comment]
this bug is still there. any updates? thanks!
