### ISSUE TITLE
Missing double quotes on the CDN page

### ISSUE THREAD

**Issue by artemist** [janpaepke/ScrollMagic#273]
Great library! I just wanted to let you know that on this page:
http://janpaepke.github.io/ScrollMagic/
the CDN script tags are missing a double quote at the end:
"//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.1/ScrollMagic.min.js

Thanks

**Comment by janpaepke** [comment]
That's correct, thanks!
It will be fixed in the next release. :)
