### ISSUE TITLE
Do effect just once

### ISSUE THREAD

**Issue by maximelebastard** [janpaepke/ScrollMagic#274]
Hello,

I want to do a tween effect just one time (and not replay it when I go out/in the trigger).

I've got this code:

        $(".post-service").each(function (index, elem) {
            var servicesTween = TweenMax.to(elem, 2, {opacity:1, ease: Expo.expoIn });
            var servicesScene = new ScrollMagic.Scene({triggerElement: elem})
                // trigger a velocity opaticy animation
                .setTween(servicesTween)
                .addTo(controller);

            servicesScene.on("end", function(target){ console.log(target) ;});
        });

I thought about destroy the scene in the "on" event. But this on event do not triggers. I also tried the "leave" event, that does not triggers.

How can I do that ?

Thanks for your helping

**Comment by janpaepke** [comment]
You're looking for the 'reverse' option. Check the docs.

**Comment by maximelebastard** [comment]
Ok, I did not found this... Sorry... Thank you !

**Comment by janpaepke** [comment]
you're welcome :)
