### ISSUE TITLE
SVG shape morph animation

### ISSUE THREAD

**Issue by jugstudio** [janpaepke/ScrollMagic#282]
Hi,

I've been trying to figure out whether it's possible to use an SVG SMIL shape morph with ScrollMagic, where the animation is controlled by the browser scroll (as in the SVG Drawing example), and how to accomplish it.  

Great work. Thanks.

**Comment by janpaepke** [comment]
Hi there!

I don't know if there's a way of directly controlling animation progress.
In theory it might be possible through markup manipulation and javascript to control the virtual playhead position of the animation. Right now I wouldn't know how though.

However this is only relevant if you want to link scroll progress to animation progress.
If you simply want to trigger a smil animation, that's totally possible.
Just attach the initialization of the respective animation to the `enter` event of a scene.

Check this out: http://jsfiddle.net/janpaepke/1c49ru8e/

If you investigate this further and find a way to control animation progress, please share!
I'm very interested! :)
