### ISSUE TITLE
ScrollMagic examples

### ISSUE THREAD

**Issue by rnxn** [janpaepke/ScrollMagic#286]
How can I get more examples using this plugin?

All examples on [examples page](http://janpaepke.github.io/ScrollMagic/examples/index.html) are down, 404.

**Comment by janpaepke** [comment]
Erm. No they're not? :)
They work just fine!
They are also included in the package, so if you download it from github, you can just view them offline.

**Comment by rnxn** [comment]
ah, ok, but online they are down.
Thanks.

**Comment by janpaepke** [comment]
They most certainly are not down.
I can open all of them... i.e. http://janpaepke.github.io/ScrollMagic/examples/basic/simple_tweening.html

Please make sure nothing's blocking them on your end.
