### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Utilities' of undefined

### ISSUE THREAD

**Issue by visualcookie** [janpaepke/ScrollMagic#292]
Hi,

I get the above error, when hitting the trigger.

main.js, where all calls are in:
```js
/**
 * SkrollMagic Scene
 */
var controller = new ScrollMagic.Controller();

// Create Scene
var scene = new ScrollMagic.Scene({
   triggerElement: '.container-About'
}).setVelocity(".about-Device", {scale: 1.2}, {duration: 1000}).addIndicators().addTo(controller);
```

Velocity and the ScrollMagic Plugin to run Velocity are getting called.

**Comment by janpaepke** [comment]
Your code seems correct: http://jsfiddle.net/s9av2y0y/

Please make sure the element ".about-Device" is present, when you hit the trigger.

**Comment by visualcookie** [comment]
It was present, that's why I find it a bit weird. I minimize the JavaScripts automatically with Grunt (maybe that can cause the problem).

But for now I did the animations with CSS. Just added a class, if the trigger is on the element.

**Comment by janpaepke** [comment]
Maybe. But that would make it a velocity issue.
Please confirm velocity runs as expected without ScrollMagic.
If it doesn't, please consult with their support forums.
If not, feel free to post your findings here.

Until then I'll consider this issue resolved from a ScrollMagic standpoint.

**Comment by rylanb** [comment]
For anyone coming afterwards to this ticket, I found that the fiddle link had both the plugin animation.velocity.js and the velocity.js plugin included, which was not how ScrollMagic downloaded. I was thinking animation.velocity.js was enough (from SM plugins from downloaded zip). I had to go to http://julian.com/research/velocity/ and add the velocity js file as well.

**Comment by thoughtpalette** [comment]
Just for the record, these are the update velocity links:
http://velocityjs.org/
https://github.com/julianshapiro/velocity

**Comment by njpatten** [comment]
I'm still having this issue, as soon as I link to the addindicators plugin. When I remove it the error disappears. Ideas?
