### ISSUE TITLE
How to link (scroll) to a specific point in a timeline?

### ISSUE THREAD

**Issue by NBOliver** [janpaepke/ScrollMagic#293]
I have set up a page similar to: http://janpaepke.github.io/ScrollMagic/examples/advanced/section_wipes_manual.html

However the timeline has 8 different chained tweens added to it. I'm struggling to find a way to link to a certain point on the timeline. I checked the scrollTo() docs, but since I only have one scene, like the demo link above, and the position of the anchors within the scene changes, I can't figure out a way to make it work. 

Any ideas would be appreciated!

**Comment by janpaepke** [comment]
Hi Oliver,

you can simply calculate the correct target scroll offset.
If all tweens in your timeline have the same length, you can simply do it by dividing the scene's duration by the number of tweens contained in the timeline.
Then add it to the [start scroll offset of the scene](http://scrollmagic.io/docs/ScrollMagic.Scene.html#scrollOffset).
like this:
```js
var numtweens = 4;
var targetNo = 2; // scroll to the start of the second tween
var startPos = ((scene.duration() / numtweens) * (targetNo - 1)) + scene.scrollOffset();
```

The better and more flexible way to do this though, is to break the timeline up and make one scene for each tween.
The reason I did it differently for the example was to make it as easy as possible.
But in your case it might be the best approach to have one scene, responsible for the pin and then one for each wipe.
You can implement their succession either by using the appropriate offsets or absolutely positioned trigger elements for each scene.

best regards,
J

**Comment by NBOliver** [comment]
I ended up converting it to multiple scenes the JS is less concise, but it works nicely. 
Your plugin is awesome - thanks for the great work!

**Comment by janpaepke** [comment]
glad you like it & could work it out. :)

**Comment by JohnGurin** [comment]
Can somebody show an example of using multiple scenes instead of timeline?
To use `controller.scrollTo(sceneN)` inside pinned containerScene.
http://codepen.io/anon/pen/PNQzem
