### ISSUE TITLE
addIndicators.min.js is 404ing on CDN

### ISSUE THREAD

**Issue by sfrdmn** [janpaepke/ScrollMagic#294]
Just a heads up.

[http://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.3/plugins/addIndicators.min.js](http://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.3/plugins/addIndicators.min.js) is 404ing right now

**Comment by janpaepke** [comment]
thx. but that's the wrong URL. :)
https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.3/plugins/debug.addIndicators.js
and
https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.3/plugins/debug.addIndicators.min.js

for all links see here: https://cdnjs.com/libraries/scrollmagic

**Comment by sfrdmn** [comment]
Oh sorry, should have specified then: that' the URL that shows up on [https://janpaepke.github.io/ScrollMagic/](https://janpaepke.github.io/ScrollMagic/)

**Comment by janpaepke** [comment]
oh, thx. that indeed should and will be fixed.
