### ISSUE TITLE
"ScrollScene is not defined" if using most recent build

### ISSUE THREAD

**Issue by MandyMadeThis** [janpaepke/ScrollMagic#295]
I'm using ScrollMagic with GSAP TweenMax. My code works if I use an old version (v1.3.0) of ScrollMagic. However if I load the current version (v2.0.3) (either by hosing it myself or loading it from the CDN) - I get a console error: "ScrollScene is not defined". Has the syntax changed in version 2?

               // Create the ScrollMagic Object
               var control = new ScrollMagic();

               //elements
                var sponsorSection = $('.sponsors');
                var p = sponsorSection.find('p.small');
                var logos = sponsorSection.find('.logo-box');

                var sponsorTL = new TimelineMax();

                // tween animations
                sponsorTL.from(p, 0.5, {top: -15, opacity: 0 })
                                  .staggerFrom(logos, 0.5,  {opacity: 0, right: -5}, 0.25);
                                  
                // ScrollMagic
                var sponsorScene = new ScrollScene({ 
                    triggerElement: sponsorSection 
                })
                .setTween(sponsorTL)
                .addTo(control);

**Comment by janpaepke** [comment]
Hi Mandy,

yes, it has. See the [changelog](https://github.com/janpaepke/ScrollMagic/blob/master/CHANGELOG.md#200-2015-02-26) for details.

If you use the uncompressed version of ScrollMagic (which you should always do for development phase) it will also notify you of this in the console.

Hint: `ScrollMagic.Controller()` & `ScrollMagic.Scene`
