### ISSUE TITLE
(intermediate value).setTween is not a function

### ISSUE THREAD

**Issue by justbane** [janpaepke/ScrollMagic#296]
I have loaded your libs from cdn like so.

```
<script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.16.1/TweenMax.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.3/ScrollMagic.min.js"></script>
```

And this code is what is being used.

```javascript

var controller = new ScrollMagic.Controller();

if ($('#triggerBlocks1').length > 0 ) {
        var headerTween1 = new TimelineMax()
            .add(TweenMax.to("#top-box2 #power-img", 1, {top: -800, opacity: 0.0, ease: Linear.easeOut}));
        // build scene
        var scene = new ScrollMagic.Scene({triggerElement: "#triggerBlocks1", duration: 1000})
            .setTween(headerTween1)
            .addTo(controller);
            
    }
```

In console I receive this error.
Uncaught TypeError: (intermediate value).setTween is not a function
Any help would be appreciated.

**Comment by janpaepke** [comment]
Always use the uncompressed version for development:
`<script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.3/ScrollMagic.js"></script>`

If you did you'd get a message in your console, telling you, that you are missing the [ScrollMagic GSAP plugin](http://scrollmagic.io/docs/animation.GSAP.html).

**Comment by justbane** [comment]
Pretty sure I copy and pasted this lib reference right from the ScrollMagic website so.... Yeah, thanks I guess I'll give it a go👌

**Comment by janpaepke** [comment]
If that's true, please provide a link :)

**Comment by justbane** [comment]
Front page of your documentation. Option 4: CDN

http://scrollmagic.io/docs/index.html

**Comment by justbane** [comment]
Thanks for the help. Some of us don't have the luxury of a development site and must complete tasks on a live site that's why I went for the minified version. Thanks for the help, like I said I'll give it a go.

**Comment by netlander** [comment]
Before a tear out the few hairs I have left I thought I'll ask the question anyway.

After scrutinising the included script tag in my html I'm still getting the `Uncaught TypeError: (intermediate value).setTween is not a function`,

And I have the non-minified version of ScrollMagic and yet not getting any explanation about what's exactly missing.

Any help would be appreciated.

**Comment by vajja-dineshchowdary** [comment]
jquery.min.js:2 Uncaught TypeError: (intermediate value).addTween is not a function

**Comment by H-Ray** [comment]
Hi @vajja-dineshchowdary 

Are you using the uncompressed version of ScrollMagic (linked below)?
`<script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.3/ScrollMagic.js"></script>`

**Comment by Professorsaurus** [comment]
I think if you are using the uncompressed version you also need to add animation.gsap into scripts...

Currently trying to find it.

**Comment by anakadote** [comment]
I came here looking to solve this issue as well. For future reference, you need to include the [animation.gsap.js plugin](http://scrollmagic.io/docs/plugins_animation.gsap.js.html) separately:

```js
<script src="//cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/TweenMax.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.6/ScrollMagic.min.js"></script>
<script src="./js/animation.gsap.js"></script>
```
