### ISSUE TITLE
Parallax Scrolling

### ISSUE THREAD

**Issue by drjorgepolanco** [janpaepke/ScrollMagic#297]
I am trying to replicate:
http://janpaepke.github.io/ScrollMagic/examples/advanced/parallax_sections.html

And I keep getting "Uncaught TypeError: (intermediate value).setTween is not a function".

This are my cdns in this exact order (removed <script> to show cleaner)
"https://cdnjs.cloudflare.com/ajax/libs/gsap/1.16.1/TweenMax.min.js"
"https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.3/ScrollMagic.min.js"
"https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.3/plugins/debug.addIndicators.min.js"

The code is the exact one copied and pasted from the source of the example link.

**Comment by UkiMiawz** [comment]
Hi I also got the same issue.
On top of that, I got this 'Linear is not a function' error

**Comment by janpaepke** [comment]
My guess is that the libraries aren't loaded when you code is executed.
Especially @UkiMiawz make sure that you have GSAP included.

Also please follow the [troubleshooting guide](https://github.com/janpaepke/ScrollMagic/blob/master/CONTRIBUTING.md#troubleshooting).

If this doesn't resolve your issue, please post a demo of it.

**Comment by trikon** [comment]
Please tell me somebody, how i can add any content(ex. section title) in box with parallax scrolling?

**Comment by janpaepke** [comment]
@trikon according to [the support guidelines](don't hijack someoneelse's post), please open a new issue for new questions.
The answer is to move the section title as well.
For more information check out this tutorial: https://scotch.io/bar-talk/ideas-and-demos-for-animating-article-headers-on-scroll

@everyoneelse: Did you manage to figure this out?

**Comment by trikon** [comment]
@janpaepke sorry, next time i will do it...
But i found a solution already. You just need to add a container with ```position: absolute``` rule in parallax parent element. But BEFORE parallax child element.
ex:
```
<div id="parallax1" class="parallaxParent">
       <div class="your-paralax-container" style="position: absolute;">Any content here.</div>
	<div style="background-image: url(../../img/example_parallax_bg1.png);"></div>
</div>
```

**Comment by janpaepke** [comment]
Well that very much depends on your setup, but yes, that's one way of approaching this.

I'm closing this issue, because it went completely off topic.
@drjorgepolanco @UkiMiawz if your issues persist, please open a new issue.
