### ISSUE TITLE
When duration is passed, the Scene starts 1px late

### ISSUE THREAD

**Issue by kasparsj** [janpaepke/ScrollMagic#299]
When you pass a duration to a Scene, the Scene actually starts 1px after the triggerElement.
This is not the case when duration is not passed in.
I had a look a the code, and I think this is because how newProgress is calculated and later evaluated.
```javascript
if (_options.duration > 0) {
	newProgress = (scrollPos - _scrollOffset.start) / (_scrollOffset.end - _scrollOffset.start);
} else {
	newProgress = scrollPos >= _scrollOffset.start ? 1 : 0;
}
```
Here you can see that:
1. when duration > 0 and scrollPos equals _scrollOffset.start, newProgress will be 0.
2. when duration <= 0 and scrollPos equals _scrollOffset.start, newProgress will be 1.

**Comment by janpaepke** [comment]
You are technically correct. But I would argue that this is still desired behavior.

A scene's start position should signify where a scene starts. Exactly, where it starts.
So triggering one px after would be unintuitive.
When using ScrollMagic to trigger an animation (duration = 0) the animation should trigger exactly at the start position of the scene.

While you are technically correct, that the progress will be 0 for scenes that do have a duration > 0, I would argue, that this still means that the scene started. As soon as we reach the start position the animation progress should be reflected by the scene progress.
And at the start position this progress is exactly 0.

So while the progress is different, depending wether the scene has a duration or not, it still reflects the appropriate progress value.

**Comment by kasparsj** [comment]
You're right, but still there is a bug related to the state, check how I fixed it for myself:
https://github.com/kasparsj/ScrollMagic/commit/77a4f724898229c67f047a3d0ac50cf67ed07b38

**Comment by janpaepke** [comment]
That is indeed a valid point!
Especially with my above definition the scene state should be "DURING" when the start position is hit.
I will change this.

**Comment by janpaepke** [comment]
thx.

**Comment by kasparsj** [comment]
thx
