### ISSUE TITLE
Save scroll position

### ISSUE THREAD

**Issue by mrortner** [janpaepke/ScrollMagic#300]
Hello,

I have a infinite scrolling page that gets populated dynamically.  Does anyone know of a good solution to maintain the scroll position once a link is clicked and then the back button is clicked to go back to the infinite scroll page?  Now it just starts at the top of the page as each page is pulled from the database.

Mike

**Comment by justinmarsan** [comment]
Assuming you have `/my-page` using pushState you can change that url when you pull new results and store the ID of the first newly shown element, such as `/my-page-to-144` then you create a new page or extend the current one to get the results from last to 144 at least when the page is loaded.

Inifite scrolling and the back buttons aren't friends, there's no easy way to deal with that, especially if you're using some CMS that's a bit rigid when dealing with pagination.

Not sure it's really related to ScrollMagic though, you'd have more luck googling your issue I think.

**Comment by mrortner** [comment]
Justin,
Thanks for the help.  This is one options we are considering.  I have been doing a good bit of searching and have a few ideas but I thought someone here may have dealt with it already.  I wonder if your solution is how google images handles their back button.  You are right, they are not friends.  

Thanks again!

**Comment by janpaepke** [comment]
As far as I know the only way to approach this at the moment is to build a custom solution, as Justin suggested.
I will close this due to limited relation to ScrollMagic.
Maybe it's worth trying to repost on StackOverflow?
