### ISSUE TITLE
scrollTo not working in firefox 36.0.4

### ISSUE THREAD

**Issue by NBOliver** [janpaepke/ScrollMagic#302]
I have set up some navigation buttons to scroll to various scenes. They work perfectly in Safari and Chrome, but not FireFox. There is no response at all in Firefox. Tried a couple different configurations, including using an anchor for the target instead of a scene object. Here's the code I'm using:

```
controller.scrollTo(function (newScrollPos) {
	$('body').animate(
		{scrollTop: newScrollPos}, 3000
	);
});

$('.btn-scroll-nav').each(function () {
	$(this).on('click', function (e) {
		e.preventDefault();
		var target = $(this).data('target');
		controller.scrollTo(eval(target));
	});
});

```

Not sure if this is on your radar as a bug, or if there's something I'm missing, but any help you can offer is appreciated. Thanks!

**Comment by NBOliver** [comment]
For others that may encounter this issue - the `scrollTo` function must animate both the `<body>` and `<html>` for this to work. So it will look like this: 

```
controller.scrollTo(function (newScrollPos) {
    $('html, body').animate(
        {scrollTop: newScrollPos}, 3000
    );
});
```
Jan - perhaps you can update the docs when you have time to incorporate this?
(http://janpaepke.github.io/ScrollMagic/docs/ScrollMagic.Controller.html#scrollTo)

**Comment by janpaepke** [comment]
thx 4 sharing.

I will update it...
