### ISSUE TITLE
Possible to run animation once?

### ISSUE THREAD

**Issue by visualcookie** [janpaepke/ScrollMagic#304]
Hi,

just a quick question: is it possible to run the animation only once the trigger has been reached? So that I scroll back the animations don't run again?

**Comment by janpaepke** [comment]
Yes, and that is a very common question.
See: https://github.com/janpaepke/ScrollMagic/issues/201, https://github.com/janpaepke/ScrollMagic/issues/274, https://github.com/janpaepke/ScrollMagic/issues/83, https://github.com/janpaepke/ScrollMagic/issues/71


Please follow the [support guidelines](https://github.com/janpaepke/ScrollMagic/blob/master/CONTRIBUTING.md#support-guidelines) and use the search first.
