### ISSUE TITLE
Have trigger element recognize entering a div

### ISSUE THREAD

**Issue by caseyctg** [janpaepke/ScrollMagic#306]
Is there a way to tell if a scene's trigger enters a div element? I have a scene which then has 5 or 6 full width 500px height elements in it. I want to see when a trigger enters an element ( basically a hit state with the trigger). 

Originally I had setup scenes on each of these inner div elements. This was causing performance issues because my page is very long and I ended up having 32 different scenes. This wasn't playing nice on mobile as it was stalling the interactions. So my thought was to reduce the amount of scenes.

However, now I have no way of telling when the trigger enters the scene's sub elements. I've tried using the progress event, but upon resizing the window, the progress location changes, so this value isn't useful as it's not reliable. 

Is there a way to set the trigger to recognize when it's entered a div as opposed to a scene?

**Comment by caseyctg** [comment]
Forgot to mention, the inner div element's heights change as you resize the window, which is why the progress event isn't reliable. On mobile, the progress event hits the div at a different % then when on desktop, tablet, etc.

**Comment by janpaepke** [comment]
Hi there,

the best way is indeed to have one scene per inner element.
The performance issues you describe are most likely not related to the number of scenes, as the processing of inactive scenes is VERY quick.
In my tests i used 100+ scenes with no problems.
What usually does cause performance issues on mobile are the "interactions" themselves: animations or other things.

So in my opinion reducing the number of scenes wouldn't really help, as long as the amount and inner workings of the "interactions" stays the same.

But if you really want to try, check this out:
Assuming all your elements have the same height at the same time you could use it to dynamically calculate the duration of a scene spanning all of them.
This way the relative progress would always be exactly the same, when reaching one of them.
Example:
Element is 500px high. 5 elements are 2500px high. Progress after first element should be `500/2500 = 0.2`.
Element is 1000px high. 5 elements are 5000px high. Progress after first element should be `1000/5000 = 0.2`

Here's how you do it in code:
```js
var sectionDuration;
// return cached value
function getSectionDuration() {
    return sectionDuration;
}
// update value
function updateSectionDuration () {
    sectionDuration = $("#element").height() * 5;
}
// update on resize
$(window).on("resize", updateSectionDuration);
// set initial value
updateSectionDuration();

// create scene
var scene = new ScrollMagic.Scene({
        triggerElement: "#sectionTrigger",
        duration: getSectionDuration // set function as duration value
    })
    .on("progress", function(e) {
        var currentSubSection = Math.floor(5 * e.progress);
        console.log(currentSubSection);
    })
    .addTo(ctrl);
```

Again I don't think this is necessary though and you should probably focus more on optimizing your interactions (i.e. using transforms over `top` or `left` tweens) than reducing the number of scenes.

**Comment by caseyctg** [comment]
Thanks for the reply. I am mainly using jQuery but I do have a lot of png images. It is odd because it works well on my iphone 6 but my first gen ipad mini stalls horribly on the interactions. I will look more at optimization. I also noticed I was creating a new controller for each scene. I made some changes and used one controller and attached all scenes to it.

**Comment by janpaepke** [comment]
yes that is definitely the way to go.
only use one controller per scroll container.

So can I consider this issue as resolved?

**Comment by caseyctg** [comment]
Yes
