### ISSUE TITLE
Update scene start after DOM removal?

### ISSUE THREAD

**Issue by JonMcL** [janpaepke/ScrollMagic#307]
My apologies if this is covered somewhere already; my searching has failed me.

If I remove DOM elements, which happen to come before the start of an existing scene, is there any way to update the start of the scene now that it is in a different scroll position?

I've tried Controller.update() and Scene.update().

The only thing that seems to work for me is to remove all remaining scenes from the controller and then add them back in.

Thanks!

**Comment by janpaepke** [comment]
Actually this should be handled automatically.
If the triggerElement position changes for whatever reason the scene's start position and progress are updated automatically.
In case it doesn't for you, it might be a bug, in which case it would be helpful if you could make a jsfiddle showcasing it.

**Comment by JonMcL** [comment]
Sorry, I _JUST_ figured it out. You are right, it is handled automatically correctly.

I had two scenes attached to the particular DOM element that I was removing. One to trigger a reveal animation and another scene to trigger the removal of the element. When I removed the element, I was only removing one of those scenes (from the controller) before removing the actual DOM element.

So this triggered a type error of "Cannot read property 'hasAttribute' of null" in the updateTriggerElementPosition function during the update. I guess because it was trying to update the un-removed scene and it's element was no longer inside the DOM.

Might be a good idea to do a sanity check on the "while (telem.parentNode.hasAttribute(PIN_SPACER_ATTRIBUTE))" loop?

**Comment by janpaepke** [comment]
I'll look into that. thx :)

**Comment by janpaepke** [comment]
Investigating this I actually stumbled over a bug: When removing the triggerElement the trigger position wasn't reset to 0 (unless explicitly triggered).
So now I fixed this and also added a a warning, if a triggerElement of a scene is removed from the DOM.

Thanks again for posting this.
