### ISSUE TITLE
Scene end without duration

### ISSUE THREAD

**Issue by omago** [janpaepke/ScrollMagic#309]
Hi Jan,

I have a question once again :). 

Lets say i have a list of articles, and on every article scene end i want to be able to do something. 

Now, if i set a scene where i have a triggerElement and duration i am able to catch "end" and "leave" events.  In this case my scene, total length of the animation is set to duration and this is totally user controlled. 

If i set a scene where i have a triggerElement and no duration, this trigger is exactly like i want it to be - it triggers my animation timeline, user has no control over it. This is the behaviour that i am trying to achieve. But, there is one more thing. I would like to be able to do something on scene end, as this scene has no duration it has no end - or the end is on the bottom of the page (i am not sure about this one). I would like to be able to have a duration but use element just like a trigger. I can make one more scene that has a trigger of "this" element and offset of the elements height and then in "enter" event i can actually catch "end" of the scene. 

My question is - Is there a better way :)? 

Best,
Domagoj

**Comment by janpaepke** [comment]
Let's clear a few things up:
In principle we distinguish between "scrollbound" and "triggered" animations.
When a scene has a duration the animation linked to it is scrollbound, which means the progress of the scrollbar will directly effect the progress of the animation.
When a scene doesn't have a duration the animation is triggered, which means as soon as the scene is reached it's played, free from the scrollbar.

Now if you want to __trigger__ two animations (one at the top of a section (i.e. an article), one at the bottom) the obvious way to go is to create two scenes. One at the top of the section, one at the bottom.
For the bottom one you can either use a separate triggerElement (the one right after the article) or you can use the same but add an offset.

If for some reason you prefer to have one scene with a duration you can't attach the animation to the scene, as then it would become scrollbound.
You could attach event listeners to listen for `start` and `end` and trigger your animations manually.
Keep in mind though, that you might have to check for `scrollDirection` to reverse the animation, when appropriate.

As you see the second approach is a lot more confusing, so my recommendation is to go with the first.

**Comment by omago** [comment]
Ok, thanks! Now i know the name "scrollbound" and "triggered" :).
