### ISSUE TITLE
scroll to scene without playing tweens

### ISSUE THREAD

**Issue by tokyobarbs** [janpaepke/ScrollMagic#314]
Hey,

I'm using the scrollTo method on my controller to scroll to specific points in my tweens within my scenes. Works well.

However, in my scenes I have autoplay video triggering. When I scroll to the scene positions these videos are being fired. When I scroll to the positions, i want to disable the tweening.

I want to prevent this. What is the best way to do this? I have tried disabling/enabling the controller before and after the scroll, but this doesn't seem to work.

Any ideas?

Thanks,
Craig

**Comment by janpaepke** [comment]
Hi Craig,

disabling and re-enabling the controller is exactly the way to go.
Remember that you need to put the "re-enable" in the callback, that is called once the automated scroll is finished.

If you create a fiddle of your problem I'd be happy to help you out.

**Comment by janpaepke** [comment]
any updates?
