### ISSUE TITLE
Loop scene, or tweens in scene

### ISSUE THREAD

**Issue by zlajaa1** [janpaepke/ScrollMagic#320]
Hi Jan,
I would like to repeat (loop infinite) tweens in one scene. Here's my code:

    var loop = new TimelineMax().add([

		//First section
		TweenMax.to('.screen-left1', 0.5, {opacity: 1, delay: 1}),		// START 1 		| duration: .5 	| END 1.5
		TweenMax.to('.screen-right1', 0.5, {opacity: 1, delay: 1.5}),	// START 1.5 	| duration: .5 	| END 2
		TweenMax.to('.screen-left1', 0.5, {opacity: 0, delay: 4}),		// START 2 		| duration: 2 	| END 4
		TweenMax.to('.screen-right1', 0.5, {opacity: 0, delay: 4}),		// START 2 		| duration: 2 	| END 4

		//Second section
		TweenMax.to('.screen-left2', 0.5, {opacity: 1, delay: 4.5}),	// START 4.5 	| duration: .5 	| END 5
		TweenMax.to('.screen-right2', 0.5, {opacity: 1, delay: 5}),		// START 5	 	| duration: .5 	| END 5.5
		TweenMax.to('.screen-left2', 0.5, {opacity: 0, delay: 7.5}),	// START 5.5 	| duration: 2 	| END 7.5
		TweenMax.to('.screen-right2', 0.5, {opacity: 0, delay: 7.5}),	// START 5.5 	| duration: 2 	| END 7.5

		//Third section
		TweenMax.to('.screen-left3', 0.5, {opacity: 1, delay: 8}),		// START 8	 	| duration: .5 	| END 8.5
		TweenMax.to('.screen-right3', 0.5, {opacity: 1, delay: 8.5}),	// START 8.5 	| duration: .5 	| END 9
		TweenMax.to('.screen-left3', 0.5, {opacity: 0, delay: 11}),		// START 9	 	| duration: 2 	| END 11
		TweenMax.to('.screen-right3', 0.5, {opacity: 0, delay: 11})		// START 9	 	| duration: 2 	| END 11

		
	]);
	var sceneOne = new ScrollMagic.Scene({triggerElement: ".case-trig2"})
		.setTween(loop)
		.triggerHook("onCenter")
		.offset(-100)
		.reverse(false)
		.addTo(controller);

So is there a way to infinite loop this animation. It's actually loop of images.

Thanks,
Zlatko

**Comment by zlajaa1** [comment]
Hi Jan,
I found a solution. The only thing that needs to be added is:
    loop.repeat(-1);

Before the sceneOne is created.

**Comment by janpaepke** [comment]
You can also do `var loop = new TimelineMax({repeat: -1})`.
See the first example here: http://scrollmagic.io/examples/advanced/advanced_tweening.html
