### ISSUE TITLE
Possible to improve performance by adding multiple scenes in one batch?

### ISSUE THREAD

**Issue by lasseyls** [janpaepke/ScrollMagic#321]
I have a scroll website I am working on, for sad reasons it's a huge one page scroll, LOADS of DOM elements, so layout takes about 500ms each time. This would be acceptable if it was just once and on resize/load only. But the way scrollmagic calls `var rect = elem.getBoundingClientRect();` in ScrollMagic._util._get.offset causes this layout to be recalculated everytime a pinned element is created.

Is it possible to somehow batch this initialization after having added all scenes to the controller, some small api change? Or is it basically impossible because getBoundingClientRect seems to force a layout? Has the creators of ScrollMagic investigated this, or can you give me any pointers to see if I can improve performance somehow?

Please see the attached Google Chrome timline screenshot. 14 seconds to initialize :-(
![screen shot 2015-05-18 at 11 10 26](https://cloud.githubusercontent.com/assets/2298345/7677777/5662e3e4-fd4f-11e4-9161-110f84bd8eb8.png)

**Comment by janpaepke** [comment]
Hi there,
getBoundingClientRect is used to determine the position of elements.
14 seconds does seem excessive though and it shoud usually take about 1 to 5 ms per element.
I'd love to inspect the page, so if you can make a public demo this would greatly help.

**Comment by lasseyls** [comment]
This took down the render town for my huge text heavy site: http://bocoup.com/weblog/text-rendering
So the problem is sort of negligible at the moment, so closing :-)
