### ISSUE TITLE
Using scrollmagic to replace images that are stored in a data attribute

### ISSUE THREAD

**Issue by ochalmers** [janpaepke/ScrollMagic#322]
Hi all. I have been using waypoints for this method previously. Basically I have a long page that contains lots of images. Instead of loading all the images i've been using waypoints to fire a function that when the user scrolls to the image it finds the data-image attribute and replaces the background with it so as not to load everything. I've only just started digging into scrollmagic, and it seems that it must be able to do this for me, but I can only find write ups on class toggling, and not functions.

Here's the code I have for the waypoints function (firing a function for each div / image) 

```js
        $('.artist_page .artistColumn').each(function(){
                        var $tgt=$(this);
                        var $bg = $tgt.attr('data-bg');
                        TweenMax.set($(this), {opacity: 0, scale: 0.8});

                        $tgt.waypoint(function(){
                             $(this).find(".artistImg").css({
                              'background-image': 'url(' + $bg + ')',
                              "background-size": "cover"});
                             //TweenMax.set($(this), {transformOrigin:'top left', opacity: 0});
                        },{
                          triggerOnce:true,
                          offset:'150%'
                        })

                        $tgt.waypoint(function(){
                             TweenMax.to($(this), Math.random(10),  {opacity: 1, scale: 1});
                        },{
                          triggerOnce:true,
                          offset:'100%'
                        })
        });
```

And here's my each function for the scrollmagic part that I was hoping to fire a function that would do the same as the above. Would I put it in a callback? 

```js
$('.release').each(function() {
              var self = $(this);
              TweenMax.set(self, {opacity: 0, scale: 0.8});
              var tween = TweenMax.fromTo(self, 2, {y: Math.floor(Math.random() * 25 + 12)}, {y: -(Math.floor(Math.random() * 25 + 12))});
              var scene = new ScrollScene({
                  triggerElement:self,
                  //duration: 500,
                  offset:'-50%'
              })
              .setTween(tween)
              .setClassToggle(self, 'scene-is-active')
              .addTo(controller);

              var makeclear = TweenMax.to(self, 2, {opacity: 1});
               var scene = new ScrollScene({
                  triggerElement:self
                  //duration: 500,
              })
               .setTween(makeclear)
              .addTo(controller);


            });
```

**Comment by janpaepke** [comment]
Hi there,
what you're describing is called lazyloading and there are plenty of plugins handling it specifically (i.e. this: http://www.appelsiini.net/projects/lazyload).
But you are correct, ScrollMagic is able to do this and if you already use it for other things on your page, you might be better of doing it with ScrollMagic.

The way you do this is by adding a listener to the [`enter` event](http://scrollmagic.io/docs/ScrollMagic.Scene.html#event:enter).
There you can swap the attributes.
Also remember to destroy the scene, as you won't be needing it any more afterwards.

**Comment by ochalmers** [comment]
Thanks alot for  your reply Jan. This was very helpful!

**Comment by janpaepke** [comment]
glad I could help.
