### ISSUE TITLE
Get the event trigger object?

### ISSUE THREAD

**Issue by ethanclevenger91** [janpaepke/ScrollMagic#323]
Is there a way I can get the event trigger object when the event is triggered. Something like...
```
new ScrollMagic.Scene({
	triggerElement: '#'+$(this).attr('id'),
	triggerHook: 'onLeave'
}).addTo(smController)
.on('enter', function(event) {
	var data = {
            	'action':'page_title',
            	'id': //the triggerElement's ID
        };
});
```

In this small example it's obviously trivial, but the idea is to apply the same anonymous function to several elements with the same class, but make a different AJAX call based on the ID.

**Comment by ethanclevenger91** [comment]
Nvm, got it -
```
$(event.target.triggerElement()).attr('id');
```

**Comment by janpaepke** [comment]
That is correct. :)
