### ISSUE TITLE
Adding scrollmagic to multiple elements on a page

### ISSUE THREAD

**Issue by ochalmers** [janpaepke/ScrollMagic#325]
Hi all, I am still getting to grips with scrollmagic, but before I dive in completely and lose countless hours tweening and tweaking, I was wondering if it is indeed the best tool to use to complete such a site as this - http://www.lecoldeclaudine.com/fr . My intention is to add subtle delayed animations to almost every element on a long blog like listing page (binded to scroll using the duration setting) and I was hoping to use scrollmagic to accomplish this, as I love greensock so much. Thanks in advance for your support.

**Comment by janpaepke** [comment]
Well good news then:
You can do exactly that.
You can either do one big timeline and add them to a scene or make one for each element.

happy diving! :)

P.S.: have a look at [`tweenChanges`](http://scrollmagic.io/docs/animation.GSAP.html#Scene.tweenChanges) to get a delayed animation effect like on your example page.

**Comment by ochalmers** [comment]
Hi Jan - I thought it best to revisit this query as I haven't been able to figure it out. I've successfully managed to create an each loop for every image to have it's own scene container and i've bound those scrolling events to the duration (100% of the viewport). This achieves part of what i'm after but the part I can't figure out is how to have the animation delay and ease to it's destinations similar to the example in my first post and also present here - http://risenchurch.com/smallgroups/ . 

Attached is my codepen - http://codepen.io/olichalmers/pen/GJwzja

Hope this makes sense! Absolutely loving scrollmagic btw now i've got the hang of things. Is there anyway i'm able to donate money / contribute? 

Thank you. :)

**Comment by ochalmers** [comment]
Wow - how did I miss your "PS" about tweenChanges. That has done it for me! Perfect, thank you.

**Comment by ochalmers** [comment]
Jan - Sorry to have to bring this up again. The loop i've set and the scenes made as a result do not appear to be following the time I am giving them, as well as the trigger being in the same place for every image when it should be relative to the image position. Are you able to view my codepen?
