### ISSUE TITLE
Problems with setClassToggle()

### ISSUE THREAD

**Issue by josespinal** [janpaepke/ScrollMagic#326]
Hi,

Whenever I use 

scene.setClassToggle(".picto-1", "animated flipInY");

I get this error: Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('animated flipInY') contains HTML space characters, which are not valid in tokens.

Weird it happens as documentation states this method of use. Any clue?

**Comment by janpaepke** [comment]
yup, that is a bug, scheduled to be fixed. :)

check here: https://github.com/janpaepke/ScrollMagic/issues/313

**Comment by josespinal** [comment]
Great. Thanks

**Comment by jeaber** [comment]
Has this been fixed yet? I just ran into this issue now.

**Comment by warhead88** [comment]
I'm on the latest version 2.0.5, and this bug is still there.
This should be fina according to documentation but I get the same error as mentioned above:
.setClassToggle(element, '-fadein -bottom')

**Comment by NicholasRowe** [comment]
I can confirm getting a bug with latest version still

**Comment by avalonstudios** [comment]
The issue is still there apparently. Trying to "animated fadeInRight" and I get the same error.

**Comment by kerryj89** [comment]
Hmm, you would think this would be a more prevalent issue and already fixed by now.  I appreciate the script anyhow!
