### ISSUE TITLE
GET 404 - on my scripts

### ISSUE THREAD

**Issue by destradafilm** [janpaepke/ScrollMagic#327]
Hi, I am new to ScrollMagic. I was having no problems with Simple Pinning, but I want to add a Tween to my Div and I'm getting an error with my js scripts loading.

I believe I have them in the proper order. 

This is the order I load the scripts:
![scripts](https://cloud.githubusercontent.com/assets/6043499/7869004/07d0b5f8-053d-11e5-8397-c444957b7169.png)

!!!!!!   THE ERROR I'M GETTTING: !!!!!!!!!!
 "animation.gsap.min.js" is 404 AND it says setTween is not a function!

HOW I CALL THE TWEEN FUNCTION:
![set tween function](https://cloud.githubusercontent.com/assets/6043499/7868958/aed2bb90-053c-11e5-8440-e369b5b46a3b.png)

My CONSOLE: 
![console_error](https://cloud.githubusercontent.com/assets/6043499/7868930/77394096-053c-11e5-95ad-ba30bf59fa34.png)

ANY SUGGESTIONS?

MUCH APPRECIATED...THANKS

**Comment by johnfmorton** [comment]
I think you're probably having a path issue with your GSAP script.

Try using their CDN instead. That might make both issues go away. 

`<script src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.16.1/TweenMax.min.js"></script>
`

Once you've got your animation library loaded successfully, the setTween function should work as expected.

**Comment by destradafilm** [comment]
Thank you so much for your suggestions. I really appreciate your help. 

Well, oddly enough my path is correct for the animation.gsap.min.js . I double checked it and moved it to another file and renamed it...still kept breaking. 
I'm wondering if I need to consider Require.js or another AMD API?

Either way, I changed it to their CDN and it fixed the 404

But, I still get some errors:

-Cannot read 'Scene' of undefined
and 
-scene1.setTween is not a function

![screen shot 2015-05-28 at 3 31 10 pm](https://cloud.githubusercontent.com/assets/6043499/7871705/e3be740e-054e-11e5-9ba1-15c672219139.png)

**Comment by johnfmorton** [comment]
I don't think you need another library like Require.js.

I was responding via my phone previous. Now I'm looking at your code more closely. I *think* you may need two separate scenes for what you're trying to accomplish. The first scene to do the pinning and a 2nd scene to control the tween. Can you try making them separate scenes (added to the same controller) and see if that changes anything?

**Comment by destradafilm** [comment]
I tried that out, and it doesn't seem to work either. 
CODE:
![screen shot 2015-05-28 at 9 52 48 pm](https://cloud.githubusercontent.com/assets/6043499/7876146/59c56bb4-0584-11e5-9a4c-669d7034417f.png)

ERROR:
![screen shot 2015-05-28 at 9 53 06 pm](https://cloud.githubusercontent.com/assets/6043499/7876150/6338f710-0584-11e5-9843-4501a506cb17.png)


SAMPLE CODE FROM SCROLL MAGIC:
I got the sample code from the Examples of Simple Animation with GSAP here:
http://scrollmagic.io/examples/basic/simple_tweening.html

<script>
	// build scene
	var scene = new ScrollMagic.Scene({triggerElement: "#trigger2", duration: 300})
					// animate color and top border in relation to scroll position
					.setTween("#animate2", {borderTop: "30px solid white", backgroundColor: "blue", scale: 0.7}) // the tween durtion can be omitted and defaults to 1
					.addIndicators({name: "2 (duration: 300)"}) // add indicators (requires plugin)
					.addTo(controller);
</script>

**Comment by johnfmorton** [comment]
I think I spotted the problem. Try loading the plugin *after* you load the main class for ScrollMagic. Does that change things?

**Comment by destradafilm** [comment]
Awesome, thanks johnfmorton! 

That did get rid of my script problems! thanks! 

BUT...
for some reason my Tween Animations wont work at all. And I get no errors. 

I get an error if I add nonsense to the :
.setTween(TweenMax.to("#red-box"), {borderTop: "30px solid white", backgroundColor: "blue"})

So it's recognizing the function, but it's not performing the animation.
