### ISSUE TITLE
Tween Animation wont work

### ISSUE THREAD

**Issue by destradafilm** [janpaepke/ScrollMagic#329]
I'm following the example found on Simple Tween Animation Example 
(http://scrollmagic.io/examples/basic/simple_tweening.html)

But I get no result. I have no problems using the .setPin to elements in my Scene...but I get nothing with Tween animations.

Here's a sample of my code:
![screen shot 2015-05-29 at 1 04 59 pm](https://cloud.githubusercontent.com/assets/6043499/7890449/58cfd184-0603-11e5-9637-b7d61d707c2c.png)

This is what my page looks like:

![screen shot 2015-05-29 at 1 02 02 pm](https://cloud.githubusercontent.com/assets/6043499/7890480/84aedf16-0603-11e5-960b-b495911483fa.png)

The red box will Pin for a duration, but will not Tween Animate. 

I also tried adding it to a Timeline and that didn't work either. 

Any suggestions?

**Comment by destradafilm** [comment]
Nevermind, I had my triggerElement and my Tween.to on the same element and that seemed to break it.

**Comment by janpaepke** [comment]
If you move the element that is also the trigger element this will cause problems. :)
If you use the uncompressed version of ScrollMagic you should also get a warning message about this.
