### ISSUE TITLE
pin jitter in chrome

### ISSUE THREAD

**Issue by laureljanej** [janpaepke/ScrollMagic#330]
I have a site set up with a pinned nav bar at the top and multiple full viewport sections that pin as you scroll through the page.  Works fine in Firefox and Safari but in Chrome the top position is recalculating on scroll and causing everything to jitter in a way that's pretty detrimental to the flow of the site.  How can I force the top position to stay at 0 when scrolling in Chrome?  I can't identify anything that'd be causing this...

**Comment by janpaepke** [comment]
Hi Laurel,

in order to help you debug this we'll need a demo.
Can you create a jsfiddle or copy your dev site to a permanent location?

regards,
J

**Comment by janpaepke** [comment]
closed until demo supplied.

**Comment by goldsteinr** [comment]
@janpaepke  I'm having this same issue. The top position is having an "elastic issue". Works fine in Chrome Win, but in Mac and FF, the top position, in PINNED elements, changes and when scroll stops, it goes back to initial value. GIF:

![scrollmagic-jitter](https://cloud.githubusercontent.com/assets/6901375/15397015/f6d9861c-1db4-11e6-8492-0400c0bf1b60.gif)

The end of the gif shows the top value. I'm using scrollmagic v2.05.

**Comment by ivarni** [comment]
I'm having this issue as well. It seems to happen just around the scene's trigger position.

I've published a demo of it on Heroku
https://quiet-caverns-38527.herokuapp.com/

Source code on Github
https://github.com/ivarni/parallax-test

```javascript
const controller = new ScrollMagic.Controller();

const scene = new ScrollMagic.Scene({
    reverse: true,
    triggerElement: '#footer',
    triggerHook: 'onEnter',
})
.setPin('#body');

controller.addScene(scene);

setTimeout(() => {
    window.scrollTo(0, scene.scrollOffset());
},200)
```

I really like this library but this is a bit of a show-stopper for me at the moment.

Now I *think* I might have fixed it with a monkey-patch but I don't know if that introduced other problems.
In the [updatePinDimensions](https://github.com/janpaepke/ScrollMagic/blob/master/scrollmagic/uncompressed/ScrollMagic.js#L2053) function I added a check to see if the height as actually changed.

```javscript
if (pinTarget.clientHeight !== css.height) {
    _util.css(_pinOptions.spacer, css);
}
```

From what I can tell that removed the jumping. Now I've no understanding of how the library works and I just found that piece of code using a DOM breakpoint so this might very well completely ruin something else.

**Comment by ekrtf** [comment]
I'm having the same issue when the element gets pinned, the elastic scrolling triggers and causes the element to jitter before being fixed. It happens only when scrolling using the wheel, everything works fine when scrolling by clicking on the scroll bar.

Anyone knows how to prevent this?
