### ISSUE TITLE
Skip some scrollTo tweens...

### ISSUE THREAD

**Issue by pstephenwille** [janpaepke/ScrollMagic#332]
I have  trigger points on scenes that comprise the sections of a larger page.  As you scroll down/up the page, those sections will scroll into view and are centered, filling up the viewport.  If you click on a nav element for one of those sections, the other section's trigger points could be hit as the page scrolls past them, to the clicked anchor point.  This causes problems ultimately ending up with the wrong section in view.  

I've disabled/enabled the controller, which works as long as I don't call controller.update(true).
Once 'update' is called, it replays each scene's scrollTo tween, and ends up on the wrong section.

What I'd like to do, is scroll to a scene and not play the scenes tween.

Hopefully, that makes sense.

**Comment by pstephenwille** [comment]
ah, looks like the trick is to use 
`TweenMax.killAll(controller);`

I wrote a separate tweening function for click events.

`

    $(document).on('click', '[href^="#"]', function (evt) {
        evt.preventDefault();
        var id = $(this).attr('href');

        controller.enabled(false);
        TweenMax.to(window, 0.5, {
            scrollTo: $(id).offset().top,
            onComplete: function () {
                controller.enabled(true);
                controller.update(true);

                TweenMax.killAll(controller);/* required */
            }
        });
    });
`

**Comment by janpaepke** [comment]
Your solution is exactly how to approach this. :)

This also resolves https://github.com/janpaepke/ScrollMagic/issues/314
