### ISSUE TITLE
laggy in safari

### ISSUE THREAD

**Issue by shamguy4** [janpaepke/ScrollMagic#334]
I discovered scrollMagic and it is awesome!
But it seems to lag a lot on safari...
maybe im using too many animations?

For each one I make a new scene and a new tween.
is that correct?

**Comment by janpaepke** [comment]
The number of scenes should not make a (noticeable) difference.

But there's a lot you can do to optimize performance.
For example animating `x` and `y` instead of `left` and `top`.

Have a look at this awesome vid: https://www.youtube.com/watch?v=R6TXuXV1bbY

**Comment by shamguy4** [comment]
actually i have been animating using classes added to the tween.
this way i keep everything in css

    var tween = TweenMax.to('#animate2', 0.5, {
    className: '+=header-bg'
    
      });
   

it nicely animates to adding .header-bg, as if i added the css classes into the function. I like it a lot.
It basically tweens a class!

Is this bad?

I also noticed that if I add css transition property on to that class (.header-bg) it loses its scroll duration abilities.

here is a quick test:
http://codepen.io/saltnpixels/pen/oXBgBj

**Comment by janpaepke** [comment]
that is true and expected behavior.
and no, it's not bad.
It will take a little longer to initialize, as GSAP needs to parse the CSS, but this shouldn't be noticable.
As I said the usual bottlenecks are somewhere else, like unnecessary paints.
Be sure to check out the video.

**Comment by shamguy4** [comment]
thank you so much!!
I watched the video.
I want to show you what im wokring on. its really cool.
https://dl.dropboxusercontent.com/u/1090829/websites/SaltnPixels.html

i saved my localhsot html page in chrome so i hope that works... :)

my only issue now is I am pinning the whole header and i wanted to move things inside at different rates so i made 2 scenes and used the same trigger element. You can see animation.js 
Otherwise I cant trigger the other scene because the scene wont move! so I used the same trigger element.... hope thats not bad.

so i pinned the scene with the text and my issues are my menu wont pop open properly on top while scrolling. And if you resize browser during the effect it doesnt go responsive.

any hint as to fixing these things would be amazingly helpful!!

I plan on writing a tutorial for my site on how I did this so I can document it and maybe help others.
My favorite is using the tween just by adding a class. Its so awesome! tweening to a class.
thanks

**Comment by shamguy4** [comment]
ok. the only issue left is the resizing the browser while something is pinned.
is that fixable or just how it is?
i dont want the pin to touch the width basically. leave it as 100%;
