### ISSUE TITLE
Browsers below IE9 problems

### ISSUE THREAD

**Issue by anevins12** [janpaepke/ScrollMagic#336]
Hi,

I understand that this plugin only works on Internet Explorers versions 9 and above, but I don't think it should break the JS on older versions.

The library automatically fires the 'addEventListener' method even when it isn't initialised, so it breaks all my other scripts in IE8 for example. 

I wonder if there's a better way to do this, to either replace 'addEventListener' with something more friendly or not fire the library when it has loaded?

Thanks!

**Comment by janpaepke** [comment]
To do that use [Conditional Comments](http://de.wikipedia.org/wiki/Conditional_Comments) and only include ScrollMagic if its IE 9 or higher.

```js
<!--[if gte IE 9]>
<script src="js/scrollmagic/uncompressed/ScrollMagic.js"></script>
<![endif]-->
```
