### ISSUE TITLE
I have just started using scrollMagic. How do I include the GSAP framework

### ISSUE THREAD

**Issue by shubhi-gupta** [janpaepke/ScrollMagic#343]

**Comment by janpaepke** [comment]
you start by sticking to the [support guidelines](https://github.com/janpaepke/ScrollMagic/blob/master/CONTRIBUTING.md#support-guidelines) and setting up a proper issue.
Don't write your whole question as the topic...

And then I suggest you include GSAP and ScrollMagic and then include the [ScrollMagic GSAP Plugin](http://scrollmagic.io/docs/animation.GSAP.html).
