### ISSUE TITLE
Issue in Wipe Animation How to add new screen

### ISSUE THREAD

**Issue by vishalpanchal21** [janpaepke/ScrollMagic#346]
Hi,
I am not able to add more screen in wipe animation with Scroll magic. If i add to five panel, starting showing error, Any buddy can help me?
Thanks!!

<script>
						$(function () { // wait for document ready
							// init
							var controller = new ScrollMagic.Controller();

							// define movement of panels
							var wipeAnimation = new TimelineMax()
								// animate to second panel
								.to("#slideContainer", 0.5, {z: -150})		
								.to("#slideContainer", 1,   {x: "-25%"})	
								.to("#slideContainer", 0.5, {z: 0})			
								// animate to third panel
								.to("#slideContainer", 0.5, {z: -150, delay: 1})
								.to("#slideContainer", 1,   {x: "-50%"})
								.to("#slideContainer", 0.5, {z: 0})
								// animate to forth panel
								.to("#slideContainer", 0.5, {z: -150, delay: 1})
								.to("#slideContainer", 1,   {x: "-75%"})
								.to("#slideContainer", 0.5, {z: 0});
								// animate to Five panel
								.to("#slideContainer", 0.5, {z: -150, delay: 1})
								.to("#slideContainer", 1,   {x: "-100%"})
								.to("#slideContainer", 0.5, {z: 0});

								

							// create scene to pin and link animation
							new ScrollMagic.Scene({
									triggerElement: "#pinContainer",
									triggerHook: "onLeave",
									duration: "800%"
								})
								.setPin("#pinContainer")
								.setTween(wipeAnimation)
								.addIndicators() // add indicators (requires plugin)
								.addTo(controller);
						});
					</script>

**Comment by janpaepke** [comment]
This is a little vague. :)
Here's how you add a new panel:
 - add the respective HTML for the panel
 - add animation in js for the panel
 - change scene duration or add new scene, if each wipe has its own scene

if this doesn't help we'll need further clarification on what exactly is your problem.

**Comment by vishalpanchal21** [comment]
Hey jan,
Big thanks for you reply.

I add 11 new pages in my animation,
& it's works but when i scroll screen is fluctuate with next image. I will
upload on demo link & share with you. If possible please help me for
resolve fluctuate other screens.

Big big thanks jan.

On Wednesday, June 17, 2015, Jan Paepke <notifications@github.com> wrote:

> Closed #346 <https://github.com/janpaepke/ScrollMagic/issues/346>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/janpaepke/ScrollMagic/issues/346#event-333049775>.
>


-- 
Sent from Gmail Mobile
