### ISSUE TITLE
Set duration as DOM object

### ISSUE THREAD

**Issue by hatchbee** [janpaepke/ScrollMagic#347]
Here is the issue/problem, I have a page with several sections(scenes) with dynamic/unequal heights. 

So for the first scene, I have to highlight nav bar as active until next scene leaves the top of the window.

I made triggerElement as "body" for first scene, keeping first nav setToggleClass "active" by default.. and duration I set to the top offset of the next sibling node. But there is a random activity on the top of the page which causes all the scenes push down. Since the duration was set before the change, the "end" triggers happens before 1st scene leave the top of the window due to old duration/offset value. How can I regularly update/re-initialize all the scenes without a glitch?

Is there any solution to this? If, then can you please guide me by an example. I referred all the examples listed + codepens + fiddles.. but couldn't possibly find a solution/hints.

How can I update/initiate scenes with new duration value?

Also, the scene's height would change after page load per user interaction like scenes are pre-default set to fix height, after user interaction each scene can individually expand to appropriate height similar to ajax loading... How to I update the "end" trigger or duration of each scene post that?

And great work on the library :100: 

Thanks in advance!

**Comment by janpaepke** [comment]
There's multiple things here:
A common misconception seems to be that you have to supply a `triggerElement`. Like all the other scene options it is (duh) _optional_.
If it's an element that doesn't move it's better to supply an offset, as an element's position needs to be constantly recalculated, where an offset stays fixed.

Now as to updating the duration there are multiple approaches.
You can catch an update (i.e. resize of the window) and then walk all the scenes in a loop and set the new duration accordingly like so: `scene.duration(200)`.

If the duration is relative to the viewport (i.e. 100% of viewport height) you can make use of the responsive duration feature: http://scrollmagic.io/examples/basic/responsive_duration.html

If there are multiple scenes using the same duration (i.e. an element's height) you can create a callback that supplies this value and define this as the duration.
This is shown here: http://scrollmagic.io/examples/expert/callback_duration.html

For more information check here: http://scrollmagic.io/docs/ScrollMagic.Scene.html#duration

Be wary that calculating element positions or heights is cpu intense and can make your site slow. Try to only update the duration when something actually changes (i.e. on resize or other user interaction).

hope this helps?

**Comment by hatchbee** [comment]
Yes, it helped! Callback duration suited my requirement. And it's working fine. 

One more question, what is refresh rate? What is the update cycle under the hood? How often Controller/Scene updates the parameters ?

**Comment by janpaepke** [comment]
Kind of like that. When you use elements as triggers their position needs to be checked constantly, since sadly they don't fire a "moved" event. This is done in the refresh cycle.
It also updates the Viewport height (for responsive duration) when using custom div elements to scroll in (as they also don't offer a resize event).

**Comment by dr-martin** [comment]
@janpaepke Your response about performance is enough for me.
Thanks!
