### ISSUE TITLE
How do I shim animation.velocity.js in Browserify

### ISSUE THREAD

**Issue by miralize** [janpaepke/ScrollMagic#348]
Trying to get Scrollmagic to function with npm & browserify, along with `browserify-shim` transform to assist with getting the shims to work. The file `animation.velocity.js` references Velocity as velocity, but Velocity's actual npm package is listed as `velocity-animate`

Here is what my package json file is like
```
 "browser": {
    "velocity": "velocity-animate/velocity",
    "velocity-ui": "velocity-animate/velocity.ui",
    "scrollmagic-velocity": "scrollmagic/scrollmagic/uncompressed/plugins/animation.velocity",
    "scrollmagic-gsap": "scrollmagic/scrollmagic/uncompressed/plugins/animation.gsap",
    "scrollmagic-jquery": "scrollmagic/scrollmagic/uncompressed/plugins/jquery.scrollmagic"
  },
  "browserify-shim": {
    "jquery": "global:$",
    "scrollmagic-jquery": {
      "depends": [
        "jquery:$"
      ]
    },
    "scrollmagic-velocity": {
      "depends": [
        "velocity:Velocity"
      ]
    }
  },
```

and here is my app.js file's requires

```
var $ = require('jquery');
var ScrollMagic = require('scrollmagic');
var Velocity = $.velocity = require('velocity-animate');
require('velocity-ui');
require('scrollmagic-jquery');
require('scrollmagic-velocity');
require('scrollmagic-gsap');
```

Unless I am missing something, this should work? Any help would be greatly appreciated

**Comment by malte-wessel** [comment]
+1

**Comment by janpaepke** [comment]
Never did this yet, sorry.
Quite swamped atm. so maybe try at velocity forums or stackoverflow?
Please report back!

**Comment by janpaepke** [comment]
any updates?

**Comment by Hagith** [comment]
+1

**Comment by miralize** [comment]
The simplest thing I can see to fix it is to reference the correct name inside the animation.velocity.js file. On line 34 I changed it from 
```factory(require('scrollmagic'), require('velocity'));```

to 
```factory(require('scrollmagic'), require('velocity-animate'));```

**Comment by Hagith** [comment]
You can use https://github.com/janpaepke/ScrollMagic/pull/388 as temporary solution, until https://github.com/julianshapiro/velocity/issues/574 is resolved.
