### ISSUE TITLE
Scroll Magic- Pin Background

### ISSUE THREAD

**Issue by poojajaiswal** [janpaepke/ScrollMagic#357]
Hi all,

From all examples of ScrollMagic Pinning effect, I have found only pinning of a text element on a div background. But what I want to achieve is - Pinning a div which has a background image and text element in it. On scroll , let the div background be pinned for some duration while text can be scrolled down as usual.

Any Ideas??

Thanks
Pooja

**Comment by janpaepke** [comment]
yes, that's possible.
Make them separate elements (the text can't be inside of the div background).
Now position the text absolutely and use z-index to put it above the background div.
Now pin the background div as you would normally.

**Comment by poojajaiswal** [comment]
Hey Jan,
That really helped, I got it working. Thanks a lot :)

**Comment by janpaepke** [comment]
glad you could work it out. :)

**Comment by tonyhrx** [comment]
Hi Jan
I did this - works great on the first pin but does not all ow for subsequent pins.

So the effect should be to have "sections". Each section has a pinned background, and some text that you are able to scroll down. After the duration of the pin, a new section comes into view and you can scroll through the text within that. Does this make sense?  Hope you can help! Been scratching my head for ages with this. Thanks

**Comment by mavnyin88** [comment]
@tonyhrx I know this is from 2 years ago - but did you ever get this to work? Im trying to create a similar effect. Any help would be greatly appreciated.
