### ISSUE TITLE
iPad, iPhone and Windows Phone

### ISSUE THREAD

**Issue by kikemx78** [janpaepke/ScrollMagic#361]
Any idea on how to make ScrollMagic work on iPad, iPhone and Windows Phone?

Here's the site I'm working on.

www.e-sant.com/freskas/index.html

**Comment by janpaepke** [comment]
Yes, there's actually two examples with detailed descriptions.
Spoiler Alert: It's not easy!

http://scrollmagic.io/examples/advanced/mobile_basic.html
http://scrollmagic.io/examples/expert/mobile_advanced.html

**Comment by kikemx78** [comment]
Hi Jan, I followed your examples and got it running good on Windows Phone and Android. It looks better on iOS but still very unstable.

Can you please take a look at my code to see what else can be done?

www.e-sant.com/freskas3/index.html

Thanx

**Comment by janpaepke** [comment]
The best advice I can give is: Don't animate `top` and `left` as they trigger repaints, which is especially problematic on mobile.
Be sure to check out this awesome video: https://www.youtube.com/watch?v=R6TXuXV1bbY
