### ISSUE TITLE
Almost OK on Windows Phone and Android. Still very unstable on iOS

### ISSUE THREAD

**Issue by kikemx78** [janpaepke/ScrollMagic#362]
Hi Jan, I followed your examples (http://janpaepke.github.io/ScrollMagic/examples/expert/mobile_advanced.html) and got it running almost perfect on Windows Phone and Android. It now looks better on iOS but still very unstable.

Can you please take a look at my code to see what else can be done?

www.e-sant.com/freskas3/index.html

Thanx

**Comment by janpaepke** [comment]
duplicate: https://github.com/janpaepke/ScrollMagic/issues/361
