### ISSUE TITLE
Remove and set pin again on previous position

### ISSUE THREAD

**Issue by pawlikdoc** [janpaepke/ScrollMagic#363]
Hi, Jan.
http://site29.twid.com.ua/
This is website i'm working on.

Generally, I create pin on '.section1' element. Also I have side popups on website (click big blue button in header).

        var spike_section_pin = new ScrollMagic.Scene({
                offset: 0,
                duration: 800
            })
            .setPin(".section1")
            .addTo(controller);  

When popup opens, pin gets broken. I tried to remove pin saving it's position when popup opens

        spike_section_pin.removePin();

This looks good in stage of opening. But I can't refresh and reset the pin when I close the popup. I tried different methods after my popup animation and class changings end. Like destroying scene, updating scene with 'true' argument or without and some more. 

            setTimeout(function() {
                spike_section_pin.destroy(true).setPin(".section1");
            }, 800);

When I try to set this pin again via 

        spike_section_pin.setPin(".section1")

another spacer is created inside current one and generally this leeds to double padding and double offset. 

I want to recreate pin in current position and get ScrollMagic functionality again. Please, look and suggest the correct way to do this.

**Comment by janpaepke** [comment]
Hi!

I can't really reproduce the problem. is the link still correct?

regards,
J

**Comment by pawlikdoc** [comment]
Hi!
Thank you for the answer.
Yes, the link is correct. Just open website and scroll for example 500px from top while background is pinned. Open side-popup in this position. Then close and you'll see the issue. 

I can find another solution for this website. But this will be unchenged at least till tomorrow.

**Comment by janpaepke** [comment]
Sorry I can't guarantee to have time to look at this in time.
Please mind the [support guidelines](https://github.com/janpaepke/ScrollMagic/blob/master/CONTRIBUTING.md#support-guidelines) that clearly state you need to provide a permanent link for your example for future reference.

Once you do so, I'd gladly take a look.
Otherwise this is specific work and not in the interest of the community.
