### ISSUE TITLE
Anchor scrolling within page section

### ISSUE THREAD

**Issue by smallhours** [janpaepke/ScrollMagic#365]
Hi,

I’m building a site where several pages have sections with vertical-scrolling "slide" content. I’d love to keep the JS as flexible as possible. Throwing it into a loop works pretty well: the script sets the section's pin duration and its '.scroller' duration/y-positioning based on how many slides there are, and generates an anchor tag for each slide, activating it when the corresponding slide hits its trigger hook.

The only problem I am having is getting these generated anchors to link back to the correct location. It sounds like ```controller.scrollTo(scene)``` is exactly what I need, and works outside of the loop, but I can’t figure out how to get it working inside the loop. What is the best way to handle this?

Here is the relevant code:

```js
new ScrollMagic.Scene({triggerElement: '#scroll-content', triggerHook: 0, duration: slides.length*scrollerHeight, offset: baseOffset})
.setPin('#scroll-content')
.setTween(TweenMax.to('#scroll-content .scroller',1,{'top': (scrollerHeight * (slides.length-1) ) *-1 }))
.addTo(controller);

for (var i=0; i<slides.length; i++) {
	
	// generate link for each slide
	$('.ticker').append($('<a>').attr({href:'#',class:'a'+i}));
	
	// update link states
	new ScrollMagic.Scene({
		triggerElement: slides[i], 
		triggerHook: 0, 
		offset: baseOffset, 
		duration: scrollerHeight
	})
	.setClassToggle('#scroll-content .ticker .a'+i, 'current').addTo(controller);
}

$('.ticker').on('click','a',function(){
	// ?
	return false;
});
```

Thank you!

**Comment by janpaepke** [comment]
Hi there,

well what you need to do is associate the link with its target.
This can be the scene or the triggerElement.
Since you use an offset scrolling to the respective triggerElement wouldn't be correct, so you are right in assuming, that `controller.scrollTo(scene)` is the way to go.

You could either store the scenes in an array and later associate each ticker link to the respective scene.
But since you generate those anyway I suggest setting them within the loop.

Without testing this I would assume it works like this:

```js
var $link;
var scene;
for (var i=0; i<slides.length; i++) {
	
	// create scene
	scene = new ScrollMagic.Scene({
		triggerElement: slides[i], 
		triggerHook: 0, 
		offset: baseOffset, 
		duration: scrollerHeight
	})
        .addTo(controller);

	// generate link for each slide
        $link = $('<a>')
                .attr({href:'#',class:'a'+i}) // you don't actually need the class but may want to keep it for css
                .on('click', function(e){
                        e.preventDefault();
                        controller.scrollTo(scene);
                });

        // add link to container
	$('.ticker').append($link);

        // set class toggle
	scene.setClassToggle($link[0], 'current');
}

```

hope this helps,
- J

**Comment by janpaepke** [comment]
did this solve your issue?

**Comment by smallhours** [comment]
I had to move the HTML around and ended up using `controller.scrollTo(#divid)` instead of the scene, but yes. Thanks!
