### ISSUE TITLE
Multiple buttons in one tween?

### ISSUE THREAD

**Issue by olleka** [janpaepke/ScrollMagic#369]
Hi.
I have a website here. http://olle.dyndns-ip.com/tunity/

ScrollMagic is controlling the movement of the blue buttons in the side of some of the sections.
It is working good.

However I want to make the code more slim and effective.
Like it is now if I add one more section I have to create one more tween and one more scene.

So the code I have for the moment is.

```javascript
var rad1 = new TweenMax.to('.fordjupning1', 1, {y: '150'});
var rad2 = new TweenMax.to('.tillbaka2', 1, {y: '450'});
var rad3 = new TweenMax.to('.tillbaka3', 1, {y: '1050'});
var rad4 = new TweenMax.to('.tillbaka4', 1, {y: '650'});
var rad5 = new TweenMax.to('.tillbaka5', 1, {y: '450'});
var rad6 = new TweenMax.to('.tillbaka6', 1, {y: '450'});
var rad7 = new TweenMax.to('.tillbaka7', 1, {y: '450'});
var rad8 = new TweenMax.to('.tillbaka8', 1, {y: '800'});
var rad9 = new TweenMax.to('.tillbaka9', 1, {y: '800'});
var rad10 = new TweenMax.to('.tillbaka10', 1, {y: '800'});


var scene1 = new ScrollMagic.Scene({
      triggerElement: '#rad1',duration: 200, offset: -50, reverse: true
    })
    .setTween(rad1)
    .addIndicators()

var scene2 = new ScrollMagic.Scene({
  triggerElement: "#rad2", duration: 400, offset: -50, reverse: true
})
.setTween(rad2)
.addIndicators()

var scene3 = new ScrollMagic.Scene({
  triggerElement: "#rad3", duration: 1000, offset: 50, reverse: true
})
.setTween(rad3)
.addIndicators() // and so on

controller.addScene([
scene1,
scene2,
scene3,
scene4,
scene5,
scene6,
scene7,
scene8,
scene9,
scene10
]);

```

I have trie the code from this question (edited for my website)
https://github.com/janpaepke/ScrollMagic/issues/215
But it does not do it.

```
$('.tillbaka10').each(function(){
    var currentStrong = this;

    var tweenStrong = new TimelineMax()
        .to(currentStrong, 1, {y: '800'});

    var scene = new ScrollMagic.Scene({triggerElement: currentStrong, duration: 800, offset: 50, reverse: true})
        .setTween(tweenStrong)
        .addTo(controller);
});
```
So how can I make this in an efficient way? With classes as the trigger? Or how is it done?

Regards
Olle

**Comment by olleka** [comment]
I got i working. Using ".tillbaka10" or whatever I like as a classname for all the buttons. Misstake I made was thinking the trigger could not be the button itself.
 
One thing though. I could not use {y: "800px"} or {top: "800px"} because of a terrible flickering and had to use {paddingTop: "800px"}
Regards
Olle

**Comment by janpaepke** [comment]
glad you could work it out
