### ISSUE TITLE
Catch window resize event to reinitialize scenes

### ISSUE THREAD

**Issue by krnlde** [janpaepke/ScrollMagic#38]
Hey Jan,
I need something to reposition scenes/tweens. I have several Tweens which are added to one pinned ScrollScene. These tweens then get `top` values by ScrollMagic depending on my window.height. And finally, these values need to be recalculated when resizing the window.

Any ideas? I already tried `controller.updateScene(scene, true);` and `scene.update();` with no effect.

With nice regards,
Kai

**Comment by jamesmthornton** [comment]
Thanksss, this saves me the window resize event. My hangup was using transforms (translate) to center elements, which were getting overwritten by my gsap tweens.

**Comment by artsyca** [comment]
The use of CSS `!important` exists for a reason and this is one of the edge cases where it would be quite applicable however a more elegant solution would be well appreciated -- it seems the whole thing falls off the rails the minute the window is resized unless carefully planned in advance

**Comment by jamesmthornton** [comment]
I think if you spend more time with it, you'll find that's only true if you aren't using percentage based positioning starting with gsap. As long as your defining your default positions, relative to the the viewport, eg. center, or 66% for a third column, with GSAP, then your tweens will be much easier to control across browser widths and device sizes.

If you are at all using number of px to position things, you are not going to have a chance to make it responsive.
