### ISSUE TITLE
Sry... I dont get it to work :/

### ISSUE THREAD

**Issue by Techassi** [janpaepke/ScrollMagic#468]
I dont get ScrollMagic to work. I dont know the issue why it doesn't want to work.

``` javascript
var controller = new ScrollMagic.Controller();
   var scene = new ScrollMagic.Scene({ triggerElement: ".trigger1", triggerHook: 'onEnter'}).setTween("#test",1,{backgroundColor: black})
       .addIndicators()
       .addTo(controller);
```

Further there are some errors showing up in the dev console:
![scrollmagicerror](https://cloud.githubusercontent.com/assets/16667167/12264836/aca48a22-b939-11e5-9c96-a7c0c0594e87.PNG)

Thanks!

**Comment by johnfmorton** [comment]
Your error says the `triggerElement` wasn't found so maybe your trigger element.

Try making the ".trigger" an ID instead of a class, i.e. make it "#trigger" instead.
