### ISSUE TITLE
Listening to events to stop video when scene leaves and play when it enters

### ISSUE THREAD

**Issue by alezzzzz** [janpaepke/ScrollMagic#48]
Im trying to stop the video when the scene leaves and the play it when it reenters, but all the events fire at once. What Im doing is this:

``` js
function callback (event) {
              if(event.type=="enter")
                   vid.play();
               else   if(event.type=="leave")
                   vid.pause();
}

// add listeners
 videoStart_scene.on("enter leave", callback);
```

It just fires all events at once and never fire another event upon reentering.

What Im doing wrong?

Thanx!!

**Comment by pythiancode** [comment]
Hey I'm having a somewhat similar problem, I want a video to start playing when the user enters a specific element, but can't seem to figure it out at all.
Here is my HTML:
`    <div id="animation2" class="row slide fullscreen-bg">
        <video id="ani2" class="fullscreen-bg__video">
            <source id="#ani2" src="img/hackettTimelapse.mp4" type="video/mp4">
        </video>
    </div>`

Here is my javascript, based on the above suggestion:
`    var ani2=document.getElementById('ani2');

    new ScrollMagic.scene({
        triggerElement: "#animation2"
    })
        .addIndicators() // add indicators (requires plugin)
        .addTo(controller)
    .on("enter", ani2.play());`

Been trying to solve this problem for a few weeks, this is the only mention I have seen of something similar - any suggestions?
