### ISSUE TITLE
Replace TweenMax / use different animation library

### ISSUE THREAD

**Issue by ochorocho** [janpaepke/ScrollMagic#481]
Hey,

is it possible to replace TweenMax with another library like velocity.js or motionUi ?

Thanks.

Cheers,
ochorocho

**Comment by Ihatetomatoes** [comment]
Yep, ScrollMagic works with velocity.js, just add the [animation.velocity.js](http://scrollmagic.io/docs/animation.Velocity.html) and you are good to go.

**Comment by ochorocho** [comment]
Thanks a bunch! i will go with velocity next time i use ScrollMagic.
