### ISSUE TITLE
Initial state when using bézier curves

### ISSUE THREAD

**Issue by bildlich** [janpaepke/ScrollMagic#486]
**[See a jsfiddle here](http://jsfiddle.net/jqmhuc9y/5/)**

I am tweening along a bézier path with 3 points.

    // bezier data
    var bezierData = {
      curviness: 1,
      autoRotate: false,
      values: [
        {x: 0,  y: 0, rotation:"40_cw"},
        {x: 20,  y: 0, rotation:"0_ccw"},
        {x: 40, y:0, rotation:"-20_ccw"}
      ]
    };

    // build tween
    var tween = new TimelineMax()
              .add(TweenMax.to("#testobj", 1, {css:{bezier: bezierData}, ease:Power1.easeInOut}));

    // create scene
    var scene = new ScrollMagic.Scene({
            triggerElement: "#testobj",
            duration: 100,
            offset: 10
        })
        .setTween(tween)
        .addTo(ctrl)
        .addIndicators();

**What I want:** The initial state of my object (i.e. before any animation has happened) should be the first bézier point, `{x: 0,  y: 0, rotation:"40_cw"}`.

**What's happening:** The initial state is the object's default style, i.e. the equivalent of `{x: 0,  y: 0, rotation:"0"}`. I assume this is the intended behaviour but have not found a way around this in the docs.

**Comment by bildlich** [comment]
Any ideas?

Let me know if the question is not clear and I'll try to clarify.

**Comment by Ihatetomatoes** [comment]
Have you tried to set the desired starting position into a simple tween, before the animation is triggered by ScrollMagic?

TweenMax.set("#testobj", {x: 0, y: 0, rotation:"40_cw"});

**Comment by bildlich** [comment]
Yes, this does the trick.
A friendly StackOverflow user modified the jsFiddle accordingly: [Demo](http://jsfiddle.net/tahirahmed/jqmhuc9y/6/)
