### ISSUE TITLE
Stuttering in chrome 50

### ISSUE THREAD

**Issue by SnowJambi** [janpaepke/ScrollMagic#529]
Not sure what the cause of this is but I spent ages trying to fix some stuttering on scrolling to eventually figure out that it was the new version of chrome causing the issue. I have a few parallax sections on my page but it's only occurring on the one at the top for some reason. 

If I move it elsewhere on the page it still stutters so I'm not sure exactly what is actually causing it. I've tried removing certain parts to see if something particular was causing the issue but it continues to stutter regardless which is baffling.

The [Parallax Sections example ](http://scrollmagic.io/examples/advanced/parallax_sections.html) shows this problem very obviously. Is anyone else able to reproduce this problem? Note that if I click middle mouse wheel and scroll that way it's perfectly smooth but if I scroll with the wheel itself that's when the issue arises, so it seems something to do with the way scrolling is handled has been changed in Chrome 50.

EDIT: Update - I've since installed Linux and it runs fine in chrome 50 on here. Not sure if it's been updated since I last tried on windows or if windows is buggy at the moment.

**Comment by tony2nite** [comment]
With the Parallax Example, In Chrome 51.0.2704.106 and Safari 9.1.1 (11601.6.17) I also get vertical stuttering (OSX 10.11.5), both with trackpad and mouse scrolling. It doesn't seem to be the speed of scrolling either, I can trigger the stutter even moving the mouse quite slowly.
