### ISSUE TITLE
Is there a way to change the trigger location?

### ISSUE THREAD

**Issue by joetemp** [janpaepke/ScrollMagic#55]
If you look on this example:

http://janpaepke.github.io/ScrollMagic/examples/basic/simple_tweening.html

You can see the trigger is in a fixed position on the right hand side. It looks to be dead center vertically. Now, when it hits the various start points with IDs "#trigger1" and "trigger2", the animations are triggered and they play out either with a duration or not.

The question is, can you change the spot of the actual trigger? Not the start points where the animations are triggered, but the trigger itself? I remember on Super Scrollorama, there was a way to have the trigger at the top or in the middle. Any tweak-ability here? Or should I just move my start points to compensate?

The only problem I have with the latter is sometimes code gets very un-sematic because you have classes/IDs that do nothing but trigger an animation.

**Comment by lukerollans** [comment]
Took me a few minutes to figure out that passing a number to `triggerHook` is interpreted as a percentage. `0` being the top of the viewport and `1` being the bottom. Thanks!

**Comment by janpaepke** [comment]
@lukerollans I'm happy to update the docs accordingly, if you could propose a better way of writing it?

**Comment by lukerollans** [comment]
Pretty much just that!

I've opened a PR
https://github.com/janpaepke/ScrollMagic/pull/331

**Comment by 1nueve** [comment]
For me http://scrollmagic.io/docs/ScrollMagic.Scene.html#triggerHook working

**Comment by ketangupta34** [comment]
in simple words use 
triggerHook: number 
property in scene number is from 0 to 1. Here, 0 points to start, 0.5 points to center and 1 point's to the end.

![Screenshot (36)](https://user-images.githubusercontent.com/42353811/79217321-4bb5e100-7e6c-11ea-9076-e55a9a78a8a7.png)
in image this sets trigger to 0.1 position
