### ISSUE TITLE
Scroll doesn't work properly on removing indicators

### ISSUE THREAD

**Issue by ravitdx** [janpaepke/ScrollMagic#561]
Hi,

I am working on web page which uses Scroll magic.It works fine until I remove the indicators.
when I remove scene.addIndicators() , tween and scroll doesn't complete.When I include the line,scroll and tween works as expected.Obviously I can't have indicators for production.please help.

thank you.

**Comment by Ihatetomatoes** [comment]
I came across a similar issue and had to review my CSS and positioning of my elements on the page.

When the indicators were turned on, they affected some of the layout and calculations.

As a general rule I always turn indicators on **only for one scene at a time** and once I am happy with the scene I remove them and move onto the next scene.

This helps to avoid a big surprise at the end of a bigger project.

**Comment by ravitdx** [comment]
Thank you for your help @Ihatetomatoes .but I solved this issue by adding `pushfollowers:true` for the last pin element of a block..even the very last one.

**Comment by Ihatetomatoes** [comment]
Great, thanks for sharing your solution, I am sure other people will find it useful too. Cheers
