### ISSUE TITLE
Accessing Specific Scenes in a Controller.

### ISSUE THREAD

**Issue by ChrisSargent** [janpaepke/ScrollMagic#576]
Hi,

Thanks for creating this, it's very cool. I've used it on a site recently here: [http://silex2.com/](http://silex2.com/) and also using it on some new sites.

On most of them I have been programmatically creating several scenes in a similar fashion to the below.

```js
var $scenes = $('.js__scene');

$scenes.each(createScene);

function createScene(i, el) {
 // create the scrollmagic scene here.
  var scene = new ScrollMagic.Scene({
    triggerElement: el
  })
  .addTo(scrollController);
}
```

Hence, I don't create a specific var or identity for each scene. How can I then access a specific scene later to manipulate it? I've tried console logging a few parts but couldn't see exactly how to do this.

Are they somehow available by querying the controller? Or stored in an array somewhere? Or somehow attached to the Dom element?

Many thanks!

Chris

**Comment by Ihatetomatoes** [comment]
They can be stored as an array if you create an empty array at the top of you javascript and then add individual scenes to it.

```javascript
var scrollController = new ScrollMagic.Controller();

// empty array
var scenes = [];

var $scenes = $('.js__scene');

$scenes.each(createScene);

function createScene(i, el) {
 // create the scrollmagic scene here.
  var scene = new ScrollMagic.Scene({
    triggerElement: el,
    duration: 300*i, // dummy duration
  })
  .setClassToggle(this, 'active')
  .addTo(scrollController);
  
  // add scene to the empty arrya
  scenes.push(scene);

}

// access duration of the scene later
console.log(scenes[1].duration());
```

[Here is a CodePen demo, check the console.log.](http://codepen.io/ihatetomatoes/pen/ade236fa3b1f7718772673238bb670da)

Hope that helps.

**Comment by ChrisSargent** [comment]
Okay, got it thanks. I had thought about doing something similar to this but wanted to check if I was missing some functionality of the controller first!

Cheers,

Chris
