### ISSUE TITLE
How to Do Wipe and Slide Effects as Seen in the Demo

### ISSUE THREAD

**Issue by etangins** [janpaepke/ScrollMagic#58]
In the demo http://janpaepke.github.io/ScrollMagic/ it shows a wipe effect and a slide effect. I don't see any examples with either of those effects. Can anyone provide me with some guidance on how to make one of them? 

Is it just a tween that triggers the effect and then the wipe and slide itself is regular JQuery or is there something in the library for those effects as well?

**Comment by MrNagoo** [comment]
I am using the section wipes on a website. However, any content that I add after the wipes, does not make the wipes go away. The last wipe just stays there, and even covers my footer. I have a duration too. any suggestion?
