### ISSUE TITLE
iPad and Mobile doesn't work.

### ISSUE THREAD

**Issue by ealvizouri** [janpaepke/ScrollMagic#60]
Hi! I'm getting in trouble trying to make it work on iPad, iPod, iPhone.... I'm using the same resources that http://janpaepke.github.io/ScrollMagic/ does. I really need your help. The loglevel 3 shows that touch events work but the TweenMax doesn't respond (animate). On desktop works nice http://alvizouri.com/cv/

Thanks!

**Comment by kikemx78** [comment]
Hi Jan, I'm also experiencing the same issue. Don't really understand what you mean by "wrapping around the content inside of the container". Here's the site I'm working on:

www.e-sant.com/freskas/index.html

Thanx and congratulations for your amazing work on developing this library. 

Enrique
