### ISSUE TITLE
video is not playing in chrome

### ISSUE THREAD

**Issue by PixupMedia** [janpaepke/ScrollMagic#642]
Hi there,

when I implement a video as HTML5
`<video preload="auto" autoplay loop width="400">
                	<source src="../myvideo.webm" type="video/webm">
                    <source src="../myvideo" type="video/ogg">
                    <source src="../myvideo.mp4" type="video/mp4">
                </video>`
that works fine an every browser.

If I insert this into a section, which is pinned via scrollmagic, the video doesn't play in chrome. All other browser are working fine; even MS Edge.

Can you help me out?

**Comment by codemasterP** [comment]
This worked for me if you place it right after the scene where you pinned the video:

$('video').get(0).play();

**Comment by PixupMedia** [comment]
Worked!
Thanks
