### ISSUE TITLE
SetPins add space to the end of IScroll

### ISSUE THREAD

**Issue by Bitneko** [janpaepke/ScrollMagic#648]
IScroll has a bottom spacing that's equivalent to the padding added by setPin(). This cause the scrollable pane to 'overscroll' it's position at the end.

**Comment by Bitneko** [comment]
Calling IScroll's refresh() method on the leave scene event of the bottom scene seem to fix the problem.

**Comment by johnny-longneck** [comment]
Can you explain how you did this? I have the same problem. Using the mobile advanced example from the demos.
