### ISSUE TITLE
All scenes are triggered when removing (jQuery remove())

### ISSUE THREAD

**Issue by Tazintosh** [janpaepke/ScrollMagic#672]
Hi folks,

Here's a very basic CodePen allowing to reproduce the issue I have: https://codepen.io/Tazintosh/pen/EmogdR

- For each ".item", I'm creating a ScrollMagic scene
- On scroll, when an item enters the view, I'm basically happening a simple "Entered" text into a div).
All of this is perfectly working, but here's the issue:

I need at some point to remove my ".parent" element from the DOM, but when doing so (by pressing the button), all "enter" events of each items of my scroll scenes are triggered.
How could I prevent this?

Thanks in advance for your time and help. Appreciated.

**Comment by jordanjtidwell** [comment]
This is old, but in your code pin destroying the parent element is making the document scroll, firing off your ScrollMagic scenes. Before removing the parent element you can disable the ScrollMagic controller to keep SM from firing off. 

`$('.actionTrigger').click(function(event){
	event.preventDefault();
	lazyLoadScrollController.enabled(false);
	$('.parent').remove();
});`

If you wanted to keep the parent element in the dom and allow your SM controller to be enabled again, you could simply toggle a class with a property of `display: none` and then enable your SM controller in a callback function `lazyLoadScrollController.enabled();`

Depends all on use case, of course!

**Comment by Tazintosh** [comment]
Oh boy!!! This was —that— simple!
(Sorry @jordanjtidwell, Hi! ^^)
Thanks a lot for your help, you just made my day!
