### ISSUE TITLE
Scrollmagic x Velocity - Only trigger animation once.

### ISSUE THREAD

**Issue by fan-r-takei** [janpaepke/ScrollMagic#679]
Hi, 
I'm using the velocity plugin.
I am able to get the animation started when it is triggered. 
The problem is that, the animation repeats itself every time I scroll back to the trigger.

This is what I have so far.

`var scene = new ScrollMagic.Scene({triggerElement: "#trigger"})
.setVelocity("#element", "transition.slideLeftBigIn", ({ opacity: 1}, {  duration:800,  easing: "easeInOut"}) )  
.addTo(controller);`

I'd like to have the animation only once, not every time I scroll to the trigger.

Please help!
Thanks.

**Comment by JAZzmiX** [comment]
add the "reverse: false"

Like:
var scene = new ScrollMagic.Scene({triggerElement: "#trigger", reverse: false}) .setVelocity("#element", "transition.slideLeftBigIn", ({ opacity: 1}, { duration:800, easing: "easeInOut"}) ) .addTo(controller);

**Comment by fan-r-takei** [comment]
@
