### ISSUE TITLE
Prallax scrolling with momentum

### ISSUE THREAD

**Issue by fschneid** [janpaepke/ScrollMagic#691]
Hello,

can anybody help me to reproduce this kind of scroll effect? 

[http://www.techstyle.com/](http://www.techstyle.com/)

I looked at their code and it's done with scrollMagic. I just can't figure out, how to add this kind of momentum, when you stop scrolling and element continues to move a little bit.

Thanks!

**Comment by thiagorossener** [comment]
Hey @fschneid, did you figured it out?
