### ISSUE TITLE
TimelineMax plays automatically (not affected by trigger)

### ISSUE THREAD

**Issue by Pipperkipper** [janpaepke/ScrollMagic#697]
Hi,

My animation starts playing on page load and isn't affected by the triggers.
Can anyone spot what I'm doing wrong?

// scene02Tl

var scene02Tl = new TimelineMax({ repeat: 10 });

scene02Tl
.fromTo(Prospect, 1, {opacity: 0, x:'-100'}, {opacity: 1, x:'0', ease: Power4.easeInOut})

var triggerTween02 = new ScrollMagic.Scene({
	triggerElement: '#slide02',
	triggerHook: 0.3,  
	offset: 300,
	duration: '50%'

})
.addIndicators()
.setTween('scene02Tl')
.addTo(controller)
;

Thanks in advance!

**Comment by RiaanP** [comment]
Remove the " " from setTween:

.setTween(scene02Tl)

Let me know if that worked?
