### ISSUE TITLE
Violation message

### ISSUE THREAD

**Issue by Nsokyi** [janpaepke/ScrollMagic#703]
Hi,

I'm getting the following message in Chrome 59, ScrollMagic v2.0.5: 
> [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.

Would this prevent ScrollMagic from working? Other than that I'm pretty sure I have everything set up correct, i.e. I can view source and inspect all the relevant links are there and are going through and this is the only error message I'm getting? 

Thanks,

**Comment by Nsokyi** [comment]
Scrap the question I got it to work by adding:

`      $(document).ready(function(){
      	initScrollMagic();
      });`

Thanks for making a great plugin. (I mean that honestly not sarcastically).

**Comment by krnlde** [comment]
Closing this issue?

**Comment by yumyo** [comment]
I still get the error no matter if I wrap ScrollMagic code in a DocReady statement

**Comment by janat08** [comment]
made new issue #793
