### ISSUE TITLE
How to test if scrollmagic is working

### ISSUE THREAD

**Issue by bbtdev** [janpaepke/ScrollMagic#704]
Hello,
Is there a way to test if scrollmagic is working? I saw the browser supprt list, but I've read browser detection should be avoid when possible. So is there anyway to test if scollmagic is working, because in case it doesn't I have to do some changes to the html elements.

Thank you very much,

**Comment by guapopaige** [comment]
Have you found any solution to your problem? I'm trying to install ScrollMagic into my HTML page but it seems that it isn't working. Any suggestions would be great!

**Comment by bbtdev** [comment]
@guapopaige No sorry, I don't use this anymore.

Sorry for the late response
