### ISSUE TITLE
Uncaught TypeError: Cannot read property 'groups' of undefined at debug.addIndicators.min.js:3

### ISSUE THREAD

**Issue by zypA13510** [janpaepke/ScrollMagic#752]
Hello, I'm having the issue with addIndicators() here. It worked fine for me until I tried to load the script dynamically and it gave me the error in the title. Code:
```JavaScript
$.noConflict();
jQuery(document).ready(function($) {
	var controller = new ScrollMagic.Controller({container: "#canvas"});
	var initScenes = function (debug) {
		var scenes = [
			new ScrollMagic.Scene({
				duration: 128,
				triggerElement: "#divDemo",
				triggerHook: 0
			})
			.setPin("#divDemo")
			.addTo(controller)
			.on("progress", function (e) {
				var val = e.progress * 128;
				$("#divDemo").css("maxHeight", val + "px");
			})
// other scenes omitted
		];
		if (debug) {
			for (i = 0; i < scenes.length; i++) {
				scenes[i].addIndicators();
			}
		}
	};
	/*
	 * Chrome Developer Tools detection by
	 * https://stackoverflow.com/q/7798748/5532169
	 */
	var devtools = /./;
	devtools.toString = function() {
		this.opened = true;
	};
	if (devtools.opened) {
		$.getScript("https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/plugins/debug.addIndicators.min.js", function() {
			initScenes(true);
		});
	} else {
		initScenes();
	}
});
```
Basically what I'm trying to do is to show the indicators (and load the debug script) only if Chrome Developer Tools is opened.
It's a strange issue because if I include the script tag and addIndicators() statically, it works just fine. The error log:
```
Uncaught TypeError: Cannot read property 'groups' of undefined
    at G (debug.addIndicators.min.js?_=1512527463285:3) <-debug.addIndicators.min.js:formatted:231
    at s.add (debug.addIndicators.min.js?_=1512527463285:3)
    at e.Scene.r.addIndicators (debug.addIndicators.min.js?_=1512527463285:3)
    at initScenes()
```
I don't know if this is related in any way to #686 .

# Environment
Windows 10 x64 v1703
Chrome 62.0.3202.94 (Official Build) (64-bit)
jQuery 3.2.1
ScrollMagic 2.0.5

**Comment by jamesmthornton** [comment]
Does it work if you reload the page with chrome dev tools still open?

**Comment by zypA13510** [comment]
Nope. As you can see the code is only called on document ready, so of course I'll have to refresh the page (and with chrome dev tools still open). But it doesn't work.

**Comment by scermat** [comment]
I've just been trying to figure out the same error (though for different reasons) and managed to solve it by changing the order of where the `debug.addIndicators` script is loaded. 

It looks like the script needs to be loaded *before* the controller is created. 

So in your case here I think you need to do the dev tools check as the first thing on document ready, and only after this point should you call `var controller = new ScrollMagic.Controller({container: "#canvas"});`

Not sure if it helps you, but seeing as I came across this post while trying to figure my issue thought I'd let you know.

**Comment by zypA13510** [comment]
Confirmed that the solution by @scermat is working. You have to create the controller after loading the debug plugin.
