### ISSUE TITLE
Pin element when it hit the top of window?

### ISSUE THREAD

**Issue by littlee** [janpaepke/ScrollMagic#768]
the "trigger" is always on RIGHT-CENTER of window, so once the element hit the middle of window, if pins, BUT what I want is, pin the element when it hit the top of window, I looking for a way to change the position of trigger (not triggerElement)  to RIGHT-TOP of window, is that possible?

![wx20180204-155151](https://user-images.githubusercontent.com/7534668/35775450-b1da70f6-09c3-11e8-9461-ae0e56f9e39d.png)

**Comment by scermat** [comment]
Specify the `triggerHook` attribute when setting up the scene.

Take a look at the scene constructor docs here: http://scrollmagic.io/docs/ScrollMagic.Scene.html#constructor

**Comment by littlee** [comment]
Cool
