### ISSUE TITLE
Stacking Pinned Elements

### ISSUE THREAD

**Issue by grewhite** [janpaepke/ScrollMagic#77]
Hi, 

I'm trying to stack pinned elements so that when you scroll to the next trigger, the above content does not scroll away.  Sorry if I'm not explaining it correctly.  

http://jsfiddle.net/yeEBa/26/

In this example, I would want the green div to stay in place once it hits the gold div for the duration. 

Thanks for your help!

**Comment by nathanvogel** [comment]
I'm in a similar situation and was trying to understand the issue, so I forked the last JSFiddle (it's not working anymore). Here's the functional version of janpaepke's solution: http://jsfiddle.net/nh2zp5oL/
