### ISSUE TITLE
Manually unpinning?

### ISSUE THREAD

**Issue by benjaminallison** [janpaepke/ScrollMagic#78]
I won't always know how "tall" my targetElement is, and want to set up a separate element to use for unpinning.

Is this possible?

**Comment by hatchbee** [comment]
is there any way to set offset of the scene dynamic based on the triggerElement ?? 

Meaning, I have a triggerElement #content , and a div above it.. which can change height, how can I calculate/maintain the offset of #content scene? 

Is resize event the only option?

Thanks! 

And thumbs up for creating great library.. :)

**Comment by nickbewley** [comment]
How to unpin an element from a div that is dynamically calculated (80vh, for example)?

**Comment by janpaepke** [comment]
@hatchbee if you use a triggerElement the offset is automatically updated if its position changes.
If I misunderstood you please post your question as a separate issue.

**Comment by stevengrimaldo** [comment]
I have a similar situation/question.

I want to pin something, a series of absolutely positioned and stacked slides in which i will use the mousewheel events to cycle through each slide with and once it gets to the last slide i then want to unpin manually. So the duration is technically up to however long it takes the user to advanced through to the final slide.

I'm basically using scrollmagic for the pinning effect and the carousel functionality is of my own custom code.
