### ISSUE TITLE
.setTween chaining

### ISSUE THREAD

**Issue by adtm** [janpaepke/ScrollMagic#788]
I don't know if it has been implemented, or it just doesn't work for me.

But I would like to have an implementation like this
```
const controller = new ScrollMagic.Controller();
 
new ScrollMagic.Scene({
  triggerElement: '#email-trigger'
})
.setTween(this.animationCircle, {
  width: 100,
  height: 100
})
.setTween(this.animationRectangle, {
  width: 50,
  height: 50,
  rotation: '45'
})
.addTo(controller);
```

and not create separate scenes to pass to the controller.

**Comment by incredible-will** [comment]
Haven't tried it yet but I was wondering the same thing and found [this in the documentation](http://scrollmagic.io/docs/animation.GSAP.html#Scene.tweenChanges):
> If you want to add multiple tweens, add them into a GSAP Timeline object and supply it instead

```javascript
// add multiple tweens, wrapped in a timeline.
var timeline = new TimelineMax();
var tween1 = TweenMax.from("obj1", 1, {x: 100});
var tween2 = TweenMax.to("obj2", 1, {y: 100});
timeline
        .add(tween1)
        .add(tween2);
scene.addTween(timeline);
```

**Comment by andwilr** [comment]
Looks like the final line in the example is wrong. Should be:

```javascript
scene.setTween(timeline);
```

**Comment by adtm** [comment]
Okay, cool and thanks!

Thought about the timeline, just didn't know how to fire them at the same time with the `-=1` parameter.
