### ISSUE TITLE
Adding "pinned" class to pinned items?

### ISSUE THREAD

**Issue by benjaminallison** [janpaepke/ScrollMagic#80]
One annoying thing with CSS is that when using percentages with a fixed element, the percentage is based off of the document, not it's parent element. So, when pinning an element that is nested in a div, the size will change if using percentages (which is common in responsive layouts) as the pinned element changes from absolute positioning to fixed.

Would it be possible to simply add a "pinned" class to items that get pinned? That way, one could easily set up some CSS to account for the change.

**Comment by 555ea** [comment]
Unavailable in version 2 😢
