### ISSUE TITLE
Uncaught TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by Obert** [janpaepke/ScrollMagic#808]
Hello
I get this issue while trying to apply an opacity on some text using Scroll Magic.
The following is the error I read in the Chromium dev tool's Console tab:

Uncaught TypeError: Cannot read property 'data' of undefined
    at f (animation.velocity.min.js:2)
    at animation.velocity.min.js:2
    at Array.forEach (<anonymous>)
    at f (animation.velocity.min.js:2)
    at v (animation.velocity.min.js:2)
    at e.Scene.<anonymous> (animation.velocity.min.js:2)
    at ScrollMagic.min.js:2
    at Array.forEach (<anonymous>)
    at e.Scene.trigger (ScrollMagic.min.js:2)
    at p (ScrollMagic.min.js:2)

The url I am working on is: [http://albertoramacciotti.it/](http://albertoramacciotti.it/)

**Comment by Obert** [comment]
I fixed the issue by using this velocity.min.js instead the previous one [https://github.com/janpaepke/ScrollMagic/blob/master/js/lib/velocity.min.js](url)

**Comment by krnlde** [comment]
For everyone getting this error. ScrollMagic or especially animation.velocity[.min].js is not compatible to Velocity v2+. It will require `Velocity.Utilities.data` as you can see in the stack trace above, where `Velocity.Utilities` is undefined.
