### ISSUE TITLE
Bug in Firefox with Top values 

### ISSUE THREAD

**Issue by BasNoticed** [janpaepke/ScrollMagic#818]
Hello there,

First of all, I love Scrollmagic. It makes everything so much easier!

But I've ran into an issue on Firefox. And I just can't fix it... Hope you guys can help me...
It's kind of a complex animation, with a lot of fixed elements.

Example: [https://dev.supplystack.com/industry/automotive](https://dev.supplystack.com/industry/automotive)

The animations work fine on Safari and Chrome, but Firefox seems to handle it differently.

Hope you guys can help!

**Comment by DarioSoller** [comment]
You could have a look into #660, maybe that helps!?

**Comment by BasNoticed** [comment]
I found the issue.. It's a dynamic animation (it's build in a CMS), and I had a animation in the loop. Firefox apparently couldn't handle that. But thanks for the help anyway!
