### ISSUE TITLE
error calling setTween()

### ISSUE THREAD

**Issue by gessdn** [janpaepke/ScrollMagic#840]
Hi there,
I am a graphic designer who is trying to build a website portfolio from scratch. I want to include some behavioural features that I found to be possible create with scrollMagic. I read the documentation, I installed scrollMagic and gsap through yarn but keep getting an error when I open the console on my browser: "error calling setTween() due to missing plugin animation.gsap"

I then tried to copy the source of the plugin and import it to my main js file, but did not work.

Can anybody help me?
I attached a few screenshots for further reference 
Thank you )

![sketch](https://user-images.githubusercontent.com/6824855/47221224-bedfb380-d3ab-11e8-94c8-fb280cde1e07.png)
![sketch1](https://user-images.githubusercontent.com/6824855/47221225-bedfb380-d3ab-11e8-9210-45e0b03035af.png)
![sketch2](https://user-images.githubusercontent.com/6824855/47221226-bedfb380-d3ab-11e8-8e40-56a03f86c65a.png)

**Comment by johanholm** [comment]
Im pretty sure you have to import the scrollmagic plugin animation.gsap, thats in your last image.
It seems you're trying to `import animation from 'gsap'`;
That will try to locate animation from gsap in your node_modules folder.
Instead try to download that plugin file and import that file instead from whereever you put it.

Example `import './animation.gsap.js'`

**Comment by gessdn** [comment]
Thank you Johan! I'll check that out
