### ISSUE TITLE
Section Wipes progress event not working?

### ISSUE THREAD

**Issue by ivanbacher** [janpaepke/ScrollMagic#843]
When attached a `progress` event listener to a section wipe scene (pinned scene), the event only gets called twice. Once at `0.00` and the second time at `1.00`. 

Is this standard?

Please see [codepen](https://codepen.io/ivan_bacher/pen/gBqary) for an example.

**Comment by soundreactor** [comment]
did you solve this?

**Comment by ivanbacher** [comment]
Awesome. Thanks for posting this.
