### ISSUE TITLE
Pinned image resizing during scrolling - followers jump (pin-spacer issue?)

### ISSUE THREAD

**Issue by austin2powers** [janpaepke/ScrollMagic#848]
Hi there,

first of all, hallo @janpaepke, impressive work with Scrollmagic, helped me a lot for our little website! :)

Have a small issue though:

I want to **resize a hero image** during scrolling from **(1) full screen height to (2) full screen width** (for responsive design, only on mobile devices).

Issue is, that during resizing the **spacer class creates unwanted white gap** and the following sections jump at the end of the scene ([screenshot here](http://toyotoro.com/scrollmagic.jpg))

I'm by no means expert, I'm just stupidly using wp-pagebuilders and managed to implement ScrollMagic with a bit of JS. So I'm pretty sure I'm a bit too stupid ;) I tried `pushFollowers: false` but this didn't solve my issue.

This is my JS:

```
jQuery(document).ready(function($) {
      
var selection = document.querySelector('.hero1') !== null;
if (selection) {

        const hero1 = document.querySelector('.hero1');

        hero1.style.position = "relative";
        hero1.style.height = window.innerHeight + "px";
        hero1.style.backgroundSize = "cover";

         if (window.innerWidth< 650){

                    var heightcalc = window.innerWidth*2/3;
             
             
                //scrolling starts
                    var controller = new ScrollMagic.Controller();                    
                    var heroscroll = new TimelineMax()
                    .add([
                        TweenMax.to(hero1,10,{height:heightcalc}),
                    ]);

                //pin scene    
                    var pinscene = new ScrollMagic.Scene({
                        triggerElement:hero1,
                        triggerHook:0,
                        duration:'100%'
                        
                    })
                    .setTween(heroscroll)
                    //.setPin(hero1,{pushFollowers: false})
                    .setPin(hero1)
                    .addTo(controller);    
 
         }
}  
});
```

And you can see the issue on [This Test Page](https://toyotoro.com/test2) (_only_ `if (window.innerWidth< 650)`).

Many thanks for a hint how to solve this!

Best
Henning

[Toyotoro.com](https://toyotoro.com)

**Comment by janpaepke** [comment]
Hi Henning,

when an element is pinned it is removed from dom flow, so it's necessary to create a spacer element to prevent the dom from changing.
If you then animate the size of your pinned element the spacer wouldn't know about it.

The solution is to have the animated element different from the pinned.

Create a container element that you use for pinning and then animate a child element in size.

Hope this helps :)

best,
J

**Comment by austin2powers** [comment]
Jan,

you are my hero 👍 

As I said, I've been pretty stupid.

Wrapping the animated object and the following content in a single container (which serves as the anchor) solved my problem.

Many thanks and greetings to Europe
Henning
