### ISSUE TITLE
Best way to reset pin on window resize

### ISSUE THREAD

**Issue by Strutsagget** [janpaepke/ScrollMagic#86]
Hi

I have a scene thats pined (100% window height) and a responsive layout. If i have scrolled passed the scene and then change window size i get a gap between the pinned scene and the next element (scene in this case). As i change the initial height off the scene div to 100% window height put the pined stays as when the pin was set.

I can change the min-height of the pinned scene (at the same time i change the div height) but that will make all the elements in the scene to be out of position.

What is the best way to reset a scene and recalculate all their values, not just duration and offset?

**Comment by mbaierl** [comment]
Hi @Strutsagget, 
I know this has been a while, but how did you solve that issue?
