### ISSUE TITLE
Pin Spacer wrong value on height resize

### ISSUE THREAD

**Issue by CHEWX** [janpaepke/ScrollMagic#871]
If you resize your height, the padding-bottom value of  `data-scrollmagic-pin-spacer` needs to match the height, however it doesn't.

When it recalculates it mis-matches them, `min-height` udpates correctly. `padding` does not.

Look at line `2068` and `console.log( _options.duration * (1 - _progress) );`

This is incorrect.

**Comment by CHEWX** [comment]
`duration: '100%'` - fixed my issue.

**Comment by aniket-shirke005** [comment]
> `duration: '100%'` - fixed my issue.

can u explain more about this? how and where to place this style? cuz I am also facing the same issue, when I resize the screen using chrome dev tools. on mobile screen the pin-spacer class calculates wrong height and padding.
