### ISSUE TITLE
GSAP 3 Error when using Scroll Magic

### ISSUE THREAD

**Issue by Anas-shamia** [janpaepke/ScrollMagic#926]
This happens when my scrollMagic trigger is activated and its only happens when i am using ScrollMagic .

I am getting this errors 

- Invalid property onOverwrite set to undefined Missing plugin? gsap.registerPlugin()

**Comment by jonkwheeler** [comment]
- https://github.com/janpaepke/ScrollMagic/issues/918
- https://github.com/janpaepke/ScrollMagic/pull/920

**Comment by jonkwheeler** [comment]
I made this to combat these issues https://github.com/jonkwheeler/ScrollScene

**Comment by Anas-shamia** [comment]
Thanks <3

**Comment by stefan-1st** [comment]
> * #918
> * #920

@jonkwheeler Thanks a lot for the solution. Would be good to mention that you have to build ScrollMagic on your own (gulp task) if you checkout the master (at the moment at least).

**Comment by Elabbasy00** [comment]
I changed all the codes mentioned and still get the same mistake
`Invalid property onOverwrite set to undefined Missing plugin? gsap.registerPlugin()`


`react_devtools_backend.js:6 00:38:17:166 (ScrollMagic.Scene) -> (animation.gsap) -> WARNING: tween was overwritten by another. To learn how to avoid this issue see here: https://github.com/janpaepke/ScrollMagic/wiki/WARNING:-tween-was-overwritten-by-another
`
