### ISSUE TITLE
how can I remove "trigger","start","end" on the left of window?

### ISSUE THREAD

**Issue by neversion** [janpaepke/ScrollMagic#95]
how can I remove "trigger","start","end" on the left of window? 
I can't ever find the dom element in debug tool.

**Comment by santoso191030** [comment]
thank you. it is not stupid question for me.

**Comment by VodooPeople** [comment]
Not stupid at all, thanks

**Comment by zzstudio-dev** [comment]
thank you~

**Comment by arskhatri5** [comment]
**markers: false,**

You need to this **markers false** if you are using scrollTrigger!
