### ISSUE TITLE
2.0.8 version release

### ISSUE THREAD

**Issue by pascaloliv** [janpaepke/ScrollMagic#975]
Hello everyone,

there is a reason why ScrollMagic `2.0.8` has never been released on npm so far ?

- [there are commits mentioning 2.0.8 on `master`](https://github.com/janpaepke/ScrollMagic/commit/376d89684737941425f753024cd52c507a28ae0f)
- the Github project page highlight `v.2.0.8` (on README.md)

`2.0.7` has been released `2019-05-29` but there is no `2.0.8`

Thanks in advance,
Olivier

**Comment by magr0s** [comment]
NPM ?

**Comment by pascaloliv** [comment]
Yes I still don't understand why the latest version on NPM is 2.0.7 : https://www.npmjs.com/package/scrollmagic

**Comment by janpaepke** [comment]
Yeah, there's a very good reason for this:
I forgot to publish it. ;)

it's done now...
