### ISSUE TITLE
Parallax on mobile

### ISSUE THREAD

**Issue by ch3rr1** [janpaepke/ScrollMagic#98]
Hi there,

I have problem with the parallax effect when viewing on mobile. The animation from the demo page works great on mobile devices. Mine doesn't. It's this stutter problem when scrolling. I only get the animation to jump from one state to another but no smooth transition. Any suggestions what I could do to fix that? Can anyone help me out here? Thanks.

**Comment by kchabra093** [comment]
can we change iScroll container to the default window? 

var myScroll = new IScroll('#example-wrapper',

**Comment by Onlyshang** [comment]
这啥？

At 2017-04-27 21:22:04, "kchabra093" <notifications@github.com> wrote:


can we change iScroll container to the default window?

var myScroll = new IScroll('#example-wrapper',
