### ISSUE TITLE
documentation is not simpler for fast going 

### ISSUE THREAD

**Issue by shahnisargweb** [janpaepke/ScrollMagic#990]
we need document to understand fast to use 
make it simple 
make it more clear 
update some links its not  working 
usage having very few description dd image also to understand output

**Comment by johnfmorton** [comment]
This is not my project, but I think there is a decent amount of documentation available. 

Are you looking at the documentation on Github? Here is a link: https://github.com/janpaepke/ScrollMagic/wiki

The first page of the documentation asks for help in creating documentation including asking that if you find a mistake or have a suggestion for improvement that you should raise an issue. 

There is also a site filled with examples here: http://scrollmagic.io/

The author also offers one-on-one support here: https://nerdpool.io/support/scrollmagic

Good luck.

-John

**Comment by dsaisho** [comment]
agree, documentation is trash. zero resources for all the api methods. examples are acceptable. however, when you have 'premium support' related to an open source project, thats a great signal you wont be getting good documentation.

**Comment by shahnisargweb** [comment]
thank you for your response
i know document is trash zero resources for all api methods but you have
some way to learn something pl share this path or doc or way
because people are used pl send and give me help
i am waiting for your reply
one agin thank you

**Comment by dsaisho** [comment]
good api docs :) 
http://scrollmagic.io/docs/ScrollMagic.Controller.html
http://scrollmagic.io/docs/ScrollMagic.Scene.html

**Comment by shahnisargweb** [comment]
Awesome, thanks!
